// =========================================================
// Learn With Rinkesh — shared formula metadata
// Used by formula-example.html (reference cards) and
// practice.html (explain popup + practice questions).
//
// Formulas with a matching entry in QUESTION_SETS (practice.html)
// get full graded practice. All others still get a real
// explanation and a free-form live sheet to try them in.
// =========================================================

const CATEGORY_ICONS = {
  'Lookup & Reference': '🔍',
  'Math & Trig': '➕',
  'Text': '🔤',
  'Logic': '⚡',
  'Date & Time': '📅',
  'Statistical': '📊',
  'Financial': '💰',
  'Information': 'ℹ️'
};

// Formulas with a full graded 10-question practice set (see practice.html)
const PRACTICE_ENABLED_IDS = ['vlookup', 'sum', 'if', 'countif'];

const FORMULA_META = [

  // ---------------- Lookup & Reference ----------------
  { id: 'vlookup', name: 'VLOOKUP', category: 'Lookup & Reference',
    syntax: '=VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])',
    description: "Looks up a value in the first column of a range and returns a value from another column, same row.",
    params: [['lookup_value','Value to search for'],['table_array','Range containing the data'],['col_index_num','Column to pull the result from'],['range_lookup','FALSE for exact match']],
    useCase: "Pulling an employee's salary into another sheet using their ID." },
  { id: 'hlookup', name: 'HLOOKUP', category: 'Lookup & Reference',
    syntax: '=HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])',
    description: "Like VLOOKUP but searches across the first row and pulls a value down a column." },
  { id: 'xlookup', name: 'XLOOKUP', category: 'Lookup & Reference',
    syntax: '=XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found])',
    description: "The modern replacement for VLOOKUP — searches any column and returns from any other, no column counting needed." },
  { id: 'index', name: 'INDEX', category: 'Lookup & Reference',
    syntax: '=INDEX(array, row_num, [column_num])',
    description: "Returns the value at a given row/column position within a range." },
  { id: 'match', name: 'MATCH', category: 'Lookup & Reference',
    syntax: '=MATCH(lookup_value, lookup_array, [match_type])',
    description: "Finds the position of a value within a range — usually paired with INDEX." },
  { id: 'choose', name: 'CHOOSE', category: 'Lookup & Reference',
    syntax: '=CHOOSE(index_num, value1, [value2], ...)',
    description: "Picks one value from a list based on a position number." },
  { id: 'indirect', name: 'INDIRECT', category: 'Lookup & Reference',
    syntax: '=INDIRECT(ref_text, [a1])',
    description: "Turns a text string into an actual cell reference." },
  { id: 'offset', name: 'OFFSET', category: 'Lookup & Reference',
    syntax: '=OFFSET(reference, rows, cols, [height], [width])',
    description: "Returns a range that's a certain number of rows/columns away from a starting cell." },
  { id: 'address', name: 'ADDRESS', category: 'Lookup & Reference',
    syntax: '=ADDRESS(row_num, column_num, [abs_num])',
    description: "Builds a cell address as text from a row and column number." },
  { id: 'row', name: 'ROW', category: 'Lookup & Reference',
    syntax: '=ROW([reference])',
    description: "Returns the row number of a reference." },
  { id: 'column', name: 'COLUMN', category: 'Lookup & Reference',
    syntax: '=COLUMN([reference])',
    description: "Returns the column number of a reference." },
  { id: 'rows', name: 'ROWS', category: 'Lookup & Reference',
    syntax: '=ROWS(array)',
    description: "Counts how many rows are in a range." },
  { id: 'columns', name: 'COLUMNS', category: 'Lookup & Reference',
    syntax: '=COLUMNS(array)',
    description: "Counts how many columns are in a range." },
  { id: 'transpose', name: 'TRANSPOSE', category: 'Lookup & Reference',
    syntax: '=TRANSPOSE(array)',
    description: "Flips a range from rows to columns or vice versa." },
  { id: 'lookup', name: 'LOOKUP', category: 'Lookup & Reference',
    syntax: '=LOOKUP(lookup_value, lookup_vector, [result_vector])',
    description: "A simpler, older lookup formula — requires sorted data." },
  { id: 'filter', name: 'FILTER', category: 'Lookup & Reference',
    syntax: '=FILTER(array, include, [if_empty])',
    description: "Returns only the rows of a range that match a condition." },
  { id: 'sort', name: 'SORT', category: 'Lookup & Reference',
    syntax: '=SORT(array, [sort_index], [sort_order])',
    description: "Sorts a range automatically as a formula, without changing the original data." },
  { id: 'unique', name: 'UNIQUE', category: 'Lookup & Reference',
    syntax: '=UNIQUE(array, [by_col], [exactly_once])',
    description: "Returns a list of distinct values from a range." },

  // ---------------- Math & Trig ----------------
  { id: 'sum', name: 'SUM', category: 'Math & Trig',
    syntax: '=SUM(number1, [number2], ...)',
    description: "Adds up all the numbers in a range — the most-used formula in Excel.",
    params: [['number1','A number or range to add'],['number2, ...','More numbers or ranges (optional)']],
    useCase: "Totaling four quarters of sales into an annual figure." },
  { id: 'sumif', name: 'SUMIF', category: 'Math & Trig',
    syntax: '=SUMIF(range, criteria, [sum_range])',
    description: "Adds up numbers, but only the ones that meet a condition." },
  { id: 'sumifs', name: 'SUMIFS', category: 'Math & Trig',
    syntax: '=SUMIFS(sum_range, criteria_range1, criteria1, ...)',
    description: "Like SUMIF but can check multiple conditions at once." },
  { id: 'sumproduct', name: 'SUMPRODUCT', category: 'Math & Trig',
    syntax: '=SUMPRODUCT(array1, [array2], ...)',
    description: "Multiplies matching items across ranges, then adds up the results." },
  { id: 'average', name: 'AVERAGE', category: 'Math & Trig',
    syntax: '=AVERAGE(number1, [number2], ...)',
    description: "Finds the mean of a set of numbers." },
  { id: 'averageif', name: 'AVERAGEIF', category: 'Math & Trig',
    syntax: '=AVERAGEIF(range, criteria, [average_range])',
    description: "Averages numbers that meet one condition." },
  { id: 'averageifs', name: 'AVERAGEIFS', category: 'Math & Trig',
    syntax: '=AVERAGEIFS(average_range, criteria_range1, criteria1, ...)',
    description: "Averages numbers that meet multiple conditions." },
  { id: 'round', name: 'ROUND', category: 'Math & Trig',
    syntax: '=ROUND(number, num_digits)',
    description: "Rounds a number to a set number of decimal places." },
  { id: 'roundup', name: 'ROUNDUP', category: 'Math & Trig',
    syntax: '=ROUNDUP(number, num_digits)',
    description: "Always rounds a number up, away from zero." },
  { id: 'rounddown', name: 'ROUNDDOWN', category: 'Math & Trig',
    syntax: '=ROUNDDOWN(number, num_digits)',
    description: "Always rounds a number down, toward zero." },
  { id: 'abs', name: 'ABS', category: 'Math & Trig',
    syntax: '=ABS(number)',
    description: "Returns the positive version of a number, ignoring its sign." },
  { id: 'power', name: 'POWER', category: 'Math & Trig',
    syntax: '=POWER(number, power)',
    description: "Raises a number to a given power." },
  { id: 'sqrt', name: 'SQRT', category: 'Math & Trig',
    syntax: '=SQRT(number)',
    description: "Returns the square root of a number." },
  { id: 'mod', name: 'MOD', category: 'Math & Trig',
    syntax: '=MOD(number, divisor)',
    description: "Returns the remainder after dividing one number by another." },
  { id: 'int', name: 'INT', category: 'Math & Trig',
    syntax: '=INT(number)',
    description: "Rounds a number down to the nearest whole number." },
  { id: 'trunc', name: 'TRUNC', category: 'Math & Trig',
    syntax: '=TRUNC(number, [num_digits])',
    description: "Cuts off the decimal part of a number without rounding." },
  { id: 'ceiling', name: 'CEILING', category: 'Math & Trig',
    syntax: '=CEILING(number, significance)',
    description: "Rounds a number up to the nearest multiple of a chosen value." },
  { id: 'floor', name: 'FLOOR', category: 'Math & Trig',
    syntax: '=FLOOR(number, significance)',
    description: "Rounds a number down to the nearest multiple of a chosen value." },
  { id: 'product', name: 'PRODUCT', category: 'Math & Trig',
    syntax: '=PRODUCT(number1, [number2], ...)',
    description: "Multiplies all the given numbers together." },
  { id: 'rand', name: 'RAND', category: 'Math & Trig',
    syntax: '=RAND()',
    description: "Returns a random decimal number between 0 and 1." },
  { id: 'randbetween', name: 'RANDBETWEEN', category: 'Math & Trig',
    syntax: '=RANDBETWEEN(bottom, top)',
    description: "Returns a random whole number between two values." },
  { id: 'pi', name: 'PI', category: 'Math & Trig',
    syntax: '=PI()',
    description: "Returns the value of pi." },
  { id: 'gcd', name: 'GCD', category: 'Math & Trig',
    syntax: '=GCD(number1, [number2], ...)',
    description: "Returns the greatest common divisor of a set of numbers." },
  { id: 'lcm', name: 'LCM', category: 'Math & Trig',
    syntax: '=LCM(number1, [number2], ...)',
    description: "Returns the least common multiple of a set of numbers." },
  { id: 'subtotal', name: 'SUBTOTAL', category: 'Math & Trig',
    syntax: '=SUBTOTAL(function_num, ref1, ...)',
    description: "Performs a calculation like SUM or AVERAGE while ignoring other subtotals in the range." },

  // ---------------- Text ----------------
  { id: 'concatenate', name: 'CONCATENATE', category: 'Text',
    syntax: '=CONCATENATE(text1, [text2], ...)',
    description: "Joins several pieces of text into one." },
  { id: 'concat', name: 'CONCAT', category: 'Text',
    syntax: '=CONCAT(text1, [text2], ...)',
    description: "The modern version of CONCATENATE, also works across ranges." },
  { id: 'textjoin', name: 'TEXTJOIN', category: 'Text',
    syntax: '=TEXTJOIN(delimiter, ignore_empty, text1, ...)',
    description: "Joins text together with a chosen separator between each piece." },
  { id: 'left', name: 'LEFT', category: 'Text',
    syntax: '=LEFT(text, [num_chars])',
    description: "Pulls a set number of characters from the start of a text string." },
  { id: 'right', name: 'RIGHT', category: 'Text',
    syntax: '=RIGHT(text, [num_chars])',
    description: "Pulls a set number of characters from the end of a text string." },
  { id: 'mid', name: 'MID', category: 'Text',
    syntax: '=MID(text, start_num, num_chars)',
    description: "Pulls characters from the middle of a text string." },
  { id: 'len', name: 'LEN', category: 'Text',
    syntax: '=LEN(text)',
    description: "Counts how many characters are in a text string." },
  { id: 'trim', name: 'TRIM', category: 'Text',
    syntax: '=TRIM(text)',
    description: "Removes extra spaces from text, leaving single spaces between words." },
  { id: 'upper', name: 'UPPER', category: 'Text',
    syntax: '=UPPER(text)',
    description: "Converts text to all uppercase." },
  { id: 'lower', name: 'LOWER', category: 'Text',
    syntax: '=LOWER(text)',
    description: "Converts text to all lowercase." },
  { id: 'proper', name: 'PROPER', category: 'Text',
    syntax: '=PROPER(text)',
    description: "Capitalizes the first letter of each word." },
  { id: 'substitute', name: 'SUBSTITUTE', category: 'Text',
    syntax: '=SUBSTITUTE(text, old_text, new_text, [instance_num])',
    description: "Replaces specific text within a string." },
  { id: 'replace', name: 'REPLACE', category: 'Text',
    syntax: '=REPLACE(old_text, start_num, num_chars, new_text)',
    description: "Replaces part of a text string based on position, not content." },
  { id: 'find', name: 'FIND', category: 'Text',
    syntax: '=FIND(find_text, within_text, [start_num])',
    description: "Finds the position of text within another string (case-sensitive)." },
  { id: 'search', name: 'SEARCH', category: 'Text',
    syntax: '=SEARCH(find_text, within_text, [start_num])',
    description: "Like FIND, but not case-sensitive and allows wildcards." },
  { id: 'text', name: 'TEXT', category: 'Text',
    syntax: '=TEXT(value, format_text)',
    description: "Converts a number into text, formatted the way you choose." },
  { id: 'value', name: 'VALUE', category: 'Text',
    syntax: '=VALUE(text)',
    description: "Converts text that looks like a number into an actual number." },
  { id: 'exact', name: 'EXACT', category: 'Text',
    syntax: '=EXACT(text1, text2)',
    description: "Checks if two text strings are exactly identical, including case." },
  { id: 'rept', name: 'REPT', category: 'Text',
    syntax: '=REPT(text, number_times)',
    description: "Repeats a piece of text a set number of times." },

  // ---------------- Logic ----------------
  { id: 'if', name: 'IF', category: 'Logic',
    syntax: '=IF(logical_test, value_if_true, value_if_false)',
    description: "Returns one value if a condition is true, another if false.",
    params: [['logical_test','The condition to check, e.g. B2>=40'],['value_if_true','Result if true'],['value_if_false','Result if false']],
    useCase: "Flagging an employee as Pass or Fail based on a score cutoff." },
  { id: 'ifs', name: 'IFS', category: 'Logic',
    syntax: '=IFS(logical_test1, value1, [logical_test2, value2], ...)',
    description: "Checks multiple conditions in order and returns the value for the first one that's true." },
  { id: 'and', name: 'AND', category: 'Logic',
    syntax: '=AND(logical1, [logical2], ...)',
    description: "Returns TRUE only if every condition given is true." },
  { id: 'or', name: 'OR', category: 'Logic',
    syntax: '=OR(logical1, [logical2], ...)',
    description: "Returns TRUE if at least one condition given is true." },
  { id: 'not', name: 'NOT', category: 'Logic',
    syntax: '=NOT(logical)',
    description: "Flips TRUE to FALSE and FALSE to TRUE." },
  { id: 'xor', name: 'XOR', category: 'Logic',
    syntax: '=XOR(logical1, [logical2], ...)',
    description: "Returns TRUE if an odd number of the given conditions are true." },
  { id: 'iferror', name: 'IFERROR', category: 'Logic',
    syntax: '=IFERROR(value, value_if_error)',
    description: "Runs a formula, but shows a fallback value instead of an error if it fails." },
  { id: 'ifna', name: 'IFNA', category: 'Logic',
    syntax: '=IFNA(value, value_if_na)',
    description: "Like IFERROR, but only catches #N/A errors specifically." },
  { id: 'switch', name: 'SWITCH', category: 'Logic',
    syntax: '=SWITCH(expression, value1, result1, [default])',
    description: "Compares one value against a list of options and returns a matching result." },

  // ---------------- Date & Time ----------------
  { id: 'today', name: 'TODAY', category: 'Date & Time',
    syntax: '=TODAY()',
    description: "Returns today's date, updated automatically." },
  { id: 'now', name: 'NOW', category: 'Date & Time',
    syntax: '=NOW()',
    description: "Returns the current date and time." },
  { id: 'date', name: 'DATE', category: 'Date & Time',
    syntax: '=DATE(year, month, day)',
    description: "Builds a real date value from separate year, month, and day numbers." },
  { id: 'datedif', name: 'DATEDIF', category: 'Date & Time',
    syntax: '=DATEDIF(start_date, end_date, unit)',
    description: "Calculates the difference between two dates in days, months, or years." },
  { id: 'day', name: 'DAY', category: 'Date & Time',
    syntax: '=DAY(serial_number)',
    description: "Pulls just the day number out of a date." },
  { id: 'month', name: 'MONTH', category: 'Date & Time',
    syntax: '=MONTH(serial_number)',
    description: "Pulls just the month number out of a date." },
  { id: 'year', name: 'YEAR', category: 'Date & Time',
    syntax: '=YEAR(serial_number)',
    description: "Pulls just the year out of a date." },
  { id: 'weekday', name: 'WEEKDAY', category: 'Date & Time',
    syntax: '=WEEKDAY(serial_number, [return_type])',
    description: "Returns which day of the week a date falls on, as a number." },
  { id: 'weeknum', name: 'WEEKNUM', category: 'Date & Time',
    syntax: '=WEEKNUM(serial_number, [return_type])',
    description: "Returns which week of the year a date falls in." },
  { id: 'eomonth', name: 'EOMONTH', category: 'Date & Time',
    syntax: '=EOMONTH(start_date, months)',
    description: "Returns the last day of the month, a set number of months away." },
  { id: 'edate', name: 'EDATE', category: 'Date & Time',
    syntax: '=EDATE(start_date, months)',
    description: "Returns a date a set number of months before or after a start date." },
  { id: 'networkdays', name: 'NETWORKDAYS', category: 'Date & Time',
    syntax: '=NETWORKDAYS(start_date, end_date, [holidays])',
    description: "Counts working days between two dates, excluding weekends." },
  { id: 'workday', name: 'WORKDAY', category: 'Date & Time',
    syntax: '=WORKDAY(start_date, days, [holidays])',
    description: "Returns the date a set number of working days from a start date." },
  { id: 'time', name: 'TIME', category: 'Date & Time',
    syntax: '=TIME(hour, minute, second)',
    description: "Builds a time value from separate hour, minute, and second numbers." },
  { id: 'hour', name: 'HOUR', category: 'Date & Time',
    syntax: '=HOUR(serial_number)',
    description: "Pulls just the hour out of a time value." },

  // ---------------- Statistical ----------------
  { id: 'count', name: 'COUNT', category: 'Statistical',
    syntax: '=COUNT(value1, [value2], ...)',
    description: "Counts how many cells in a range contain numbers." },
  { id: 'counta', name: 'COUNTA', category: 'Statistical',
    syntax: '=COUNTA(value1, [value2], ...)',
    description: "Counts how many cells in a range are not empty." },
  { id: 'countblank', name: 'COUNTBLANK', category: 'Statistical',
    syntax: '=COUNTBLANK(range)',
    description: "Counts how many cells in a range are empty." },
  { id: 'countif', name: 'COUNTIF', category: 'Statistical',
    syntax: '=COUNTIF(range, criteria)',
    description: "Counts how many cells in a range match a condition.",
    params: [['range','Cells to check'],['criteria','Condition to match, e.g. "Finance"']],
    useCase: "Counting how many employees belong to one department." },
  { id: 'countifs', name: 'COUNTIFS', category: 'Statistical',
    syntax: '=COUNTIFS(criteria_range1, criteria1, ...)',
    description: "Like COUNTIF, but can check multiple conditions at once." },
  { id: 'max', name: 'MAX', category: 'Statistical',
    syntax: '=MAX(number1, [number2], ...)',
    description: "Returns the largest number in a set." },
  { id: 'min', name: 'MIN', category: 'Statistical',
    syntax: '=MIN(number1, [number2], ...)',
    description: "Returns the smallest number in a set." },
  { id: 'maxifs', name: 'MAXIFS', category: 'Statistical',
    syntax: '=MAXIFS(max_range, criteria_range1, criteria1, ...)',
    description: "Returns the largest number in a range that meets given conditions." },
  { id: 'minifs', name: 'MINIFS', category: 'Statistical',
    syntax: '=MINIFS(min_range, criteria_range1, criteria1, ...)',
    description: "Returns the smallest number in a range that meets given conditions." },
  { id: 'median', name: 'MEDIAN', category: 'Statistical',
    syntax: '=MEDIAN(number1, [number2], ...)',
    description: "Returns the middle value in a set of numbers." },
  { id: 'mode', name: 'MODE', category: 'Statistical',
    syntax: '=MODE(number1, [number2], ...)',
    description: "Returns the most frequently occurring number in a set." },
  { id: 'stdev', name: 'STDEV', category: 'Statistical',
    syntax: '=STDEV(number1, [number2], ...)',
    description: "Measures how spread out a set of numbers is from the average." },
  { id: 'var', name: 'VAR', category: 'Statistical',
    syntax: '=VAR(number1, [number2], ...)',
    description: "Measures the variance of a set of numbers." },
  { id: 'rank', name: 'RANK', category: 'Statistical',
    syntax: '=RANK(number, ref, [order])',
    description: "Returns the rank of a number within a list of numbers." },
  { id: 'large', name: 'LARGE', category: 'Statistical',
    syntax: '=LARGE(array, k)',
    description: "Returns the k-th largest value in a set — e.g. the 2nd biggest sale." },
  { id: 'small', name: 'SMALL', category: 'Statistical',
    syntax: '=SMALL(array, k)',
    description: "Returns the k-th smallest value in a set." },

  // ---------------- Financial ----------------
  { id: 'pmt', name: 'PMT', category: 'Financial',
    syntax: '=PMT(rate, nper, pv, [fv], [type])',
    description: "Calculates the fixed periodic payment for a loan." },
  { id: 'fv', name: 'FV', category: 'Financial',
    syntax: '=FV(rate, nper, pmt, [pv], [type])',
    description: "Calculates the future value of an investment based on regular payments." },
  { id: 'pv', name: 'PV', category: 'Financial',
    syntax: '=PV(rate, nper, pmt, [fv], [type])',
    description: "Calculates the present value of a series of future payments." },
  { id: 'npv', name: 'NPV', category: 'Financial',
    syntax: '=NPV(rate, value1, [value2], ...)',
    description: "Calculates the net present value of a series of cash flows." },
  { id: 'irr', name: 'IRR', category: 'Financial',
    syntax: '=IRR(values, [guess])',
    description: "Estimates the internal rate of return for a series of cash flows." },
  { id: 'rate', name: 'RATE', category: 'Financial',
    syntax: '=RATE(nper, pmt, pv, [fv], [type])',
    description: "Calculates the interest rate per period for a loan or investment." },
  { id: 'nper', name: 'NPER', category: 'Financial',
    syntax: '=NPER(rate, pmt, pv, [fv], [type])',
    description: "Calculates how many payment periods are needed to pay off a loan." },

  // ---------------- Information ----------------
  { id: 'isblank', name: 'ISBLANK', category: 'Information',
    syntax: '=ISBLANK(value)',
    description: "Checks whether a cell is empty." },
  { id: 'iserror', name: 'ISERROR', category: 'Information',
    syntax: '=ISERROR(value)',
    description: "Checks whether a value is any kind of error." },
  { id: 'isnumber', name: 'ISNUMBER', category: 'Information',
    syntax: '=ISNUMBER(value)',
    description: "Checks whether a value is a number." },
  { id: 'istext', name: 'ISTEXT', category: 'Information',
    syntax: '=ISTEXT(value)',
    description: "Checks whether a value is text." },
  { id: 'isna', name: 'ISNA', category: 'Information',
    syntax: '=ISNA(value)',
    description: "Checks whether a value is the #N/A error specifically." },
  { id: 'iseven', name: 'ISEVEN', category: 'Information',
    syntax: '=ISEVEN(number)',
    description: "Checks whether a number is even." },
  { id: 'isodd', name: 'ISODD', category: 'Information',
    syntax: '=ISODD(number)',
    description: "Checks whether a number is odd." }
];
