// =========================================================
// Learn With Rinkesh — shared formula metadata
// Used by formula-example.html (reference cards) and
// practice.html (explain popup + practice questions).
//
// Formulas with a matching entry in QUESTION_SETS (practice.html)
// get full graded practice. All others still get a real
// explanation and a free-form live sheet to try them in.
// =========================================================

const CATEGORY_ORDER = ['Math & Trig', 'Text', 'Logic', 'Date & Time', 'Statistical', 'Financial', 'Information', 'Database', 'Engineering', 'Web', 'Cube', 'Compatibility', 'Lookup & Reference'];

const CATEGORY_ICONS = {
  'Lookup & Reference': '🔍',
  'Math & Trig': '➕',
  'Text': '🔤',
  'Logic': '⚡',
  'Date & Time': '📅',
  'Statistical': '📊',
  'Financial': '💰',
  'Information': 'ℹ️',
  'Database': '🗄️',
  'Engineering': '⚙️',
  'Web': '🌐',
  'Cube': '🧊',
  'Compatibility': '🕰️'
};

// Formulas with a full graded 10-question practice set (see practice.html)
const PRACTICE_ENABLED_IDS = ['vlookup', 'sum', 'if', 'countif', 'hlookup', 'index', 'match', 'choose'];

// To add a tutorial video for a formula later, add a videoUrl field to its
// entry below, e.g.: videoUrl: 'https://youtu.be/XXXXXXXXXXX'
// The video icon next to that formula in the Practice sidebar will
// automatically light up and become clickable once that field is set.

const FORMULA_META = [

  // ---------------- Lookup & Reference ----------------
  { id: 'vlookup', name: 'VLOOKUP', category: 'Lookup & Reference',
    syntax: '=VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])',
    description: "Looks up a value in the first column of a range and returns a value from another column, same row.",
    params: [['lookup_value','Value to search for'],['table_array','Range containing the data'],['col_index_num','Column to pull the result from'],['range_lookup','FALSE for exact match']],
    useCase: "Pulling an employee's salary into another sheet using their ID." },
  { id: 'hlookup', name: 'HLOOKUP', category: 'Lookup & Reference',
    syntax: '=HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])',
    description: "Like VLOOKUP but searches across the first row and pulls a value down a column.",
    params: [['lookup_value','Value to search for in the top row'],['table_array','Range containing the data'],['row_index_num','Which row (from the top) to pull the result from'],['range_lookup','FALSE for exact match']],
    useCase: "Pulling a specific month's figure from a report laid out horizontally instead of in columns." },
  { id: 'xlookup', name: 'XLOOKUP', category: 'Lookup & Reference',
    syntax: '=XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found])',
    description: "The modern replacement for VLOOKUP — searches any column and returns from any other, no column counting needed." },
  { id: 'index', name: 'INDEX', category: 'Lookup & Reference',
    syntax: '=INDEX(array, row_num, [column_num])',
    description: "Returns the value at a given row/column position within a range.",
    params: [['array','The range to pull from'],['row_num','Which row within the range'],['column_num','Which column within the range (optional for single-column ranges)']],
    useCase: "Pulling the Nth item from a list — often paired with MATCH to look up in any direction." },
  { id: 'match', name: 'MATCH', category: 'Lookup & Reference',
    syntax: '=MATCH(lookup_value, lookup_array, [match_type])',
    description: "Finds the position of a value within a range — usually paired with INDEX.",
    params: [['lookup_value','Value to search for'],['lookup_array','Range to search in'],['match_type','0 for exact match']],
    useCase: "Finding exactly where a value sits in a list, so INDEX can pull the matching row." },
  { id: 'choose', name: 'CHOOSE', category: 'Lookup & Reference',
    syntax: '=CHOOSE(index_num, value1, [value2], ...)',
    description: "Picks one value from a list based on a position number.",
    params: [['index_num','Which item to return (1-based position)'],['value1, value2, ...','The list of items to choose from']],
    useCase: "Turning a numeric rating (1–5) into a readable label like Poor, Fair, Good, Great, Excellent." },
  { id: 'indirect', name: 'INDIRECT', category: 'Lookup & Reference',
    syntax: '=INDIRECT(ref_text, [a1])',
    description: "Turns a text string into an actual cell reference." },
  { id: 'offset', name: 'OFFSET', category: 'Lookup & Reference',
    syntax: '=OFFSET(reference, rows, cols, [height], [width])',
    description: "Returns a range that's a certain number of rows/columns away from a starting cell." },
  { id: 'address', name: 'ADDRESS', category: 'Lookup & Reference',
    syntax: '=ADDRESS(row_num, column_num, [abs_num])',
    description: "Builds a cell address as text from a row and column number." },
  { id: 'row', name: 'ROW', category: 'Lookup & Reference',
    syntax: '=ROW([reference])',
    description: "Returns the row number of a reference." },
  { id: 'column', name: 'COLUMN', category: 'Lookup & Reference',
    syntax: '=COLUMN([reference])',
    description: "Returns the column number of a reference." },
  { id: 'rows', name: 'ROWS', category: 'Lookup & Reference',
    syntax: '=ROWS(array)',
    description: "Counts how many rows are in a range." },
  { id: 'columns', name: 'COLUMNS', category: 'Lookup & Reference',
    syntax: '=COLUMNS(array)',
    description: "Counts how many columns are in a range." },
  { id: 'transpose', name: 'TRANSPOSE', category: 'Lookup & Reference',
    syntax: '=TRANSPOSE(array)',
    description: "Flips a range from rows to columns or vice versa." },
  { id: 'lookup', name: 'LOOKUP', category: 'Lookup & Reference',
    syntax: '=LOOKUP(lookup_value, lookup_vector, [result_vector])',
    description: "A simpler, older lookup formula — requires sorted data." },
  { id: 'filter', name: 'FILTER', category: 'Lookup & Reference',
    syntax: '=FILTER(array, include, [if_empty])',
    description: "Returns only the rows of a range that match a condition." },
  { id: 'sort', name: 'SORT', category: 'Lookup & Reference',
    syntax: '=SORT(array, [sort_index], [sort_order])',
    description: "Sorts a range automatically as a formula, without changing the original data." },
  { id: 'unique', name: 'UNIQUE', category: 'Lookup & Reference',
    syntax: '=UNIQUE(array, [by_col], [exactly_once])',
    description: "Returns a list of distinct values from a range." },

  // ---------------- Math & Trig ----------------
  { id: 'sum', name: 'SUM', category: 'Math & Trig',
    syntax: '=SUM(number1, [number2], ...)',
    description: "Adds up all the numbers in a range — the most-used formula in Excel.",
    params: [['number1','A number or range to add'],['number2, ...','More numbers or ranges (optional)']],
    useCase: "Totaling four quarters of sales into an annual figure." },
  { id: 'sumif', name: 'SUMIF', category: 'Math & Trig',
    syntax: '=SUMIF(range, criteria, [sum_range])',
    description: "Adds up numbers, but only the ones that meet a condition." },
  { id: 'sumifs', name: 'SUMIFS', category: 'Math & Trig',
    syntax: '=SUMIFS(sum_range, criteria_range1, criteria1, ...)',
    description: "Like SUMIF but can check multiple conditions at once." },
  { id: 'sumproduct', name: 'SUMPRODUCT', category: 'Math & Trig',
    syntax: '=SUMPRODUCT(array1, [array2], ...)',
    description: "Multiplies matching items across ranges, then adds up the results." },
  { id: 'average', name: 'AVERAGE', category: 'Math & Trig',
    syntax: '=AVERAGE(number1, [number2], ...)',
    description: "Finds the mean of a set of numbers." },
  { id: 'averageif', name: 'AVERAGEIF', category: 'Math & Trig',
    syntax: '=AVERAGEIF(range, criteria, [average_range])',
    description: "Averages numbers that meet one condition." },
  { id: 'averageifs', name: 'AVERAGEIFS', category: 'Math & Trig',
    syntax: '=AVERAGEIFS(average_range, criteria_range1, criteria1, ...)',
    description: "Averages numbers that meet multiple conditions." },
  { id: 'round', name: 'ROUND', category: 'Math & Trig',
    syntax: '=ROUND(number, num_digits)',
    description: "Rounds a number to a set number of decimal places." },
  { id: 'roundup', name: 'ROUNDUP', category: 'Math & Trig',
    syntax: '=ROUNDUP(number, num_digits)',
    description: "Always rounds a number up, away from zero." },
  { id: 'rounddown', name: 'ROUNDDOWN', category: 'Math & Trig',
    syntax: '=ROUNDDOWN(number, num_digits)',
    description: "Always rounds a number down, toward zero." },
  { id: 'abs', name: 'ABS', category: 'Math & Trig',
    syntax: '=ABS(number)',
    description: "Returns the positive version of a number, ignoring its sign." },
  { id: 'power', name: 'POWER', category: 'Math & Trig',
    syntax: '=POWER(number, power)',
    description: "Raises a number to a given power." },
  { id: 'sqrt', name: 'SQRT', category: 'Math & Trig',
    syntax: '=SQRT(number)',
    description: "Returns the square root of a number." },
  { id: 'mod', name: 'MOD', category: 'Math & Trig',
    syntax: '=MOD(number, divisor)',
    description: "Returns the remainder after dividing one number by another." },
  { id: 'int', name: 'INT', category: 'Math & Trig',
    syntax: '=INT(number)',
    description: "Rounds a number down to the nearest whole number." },
  { id: 'trunc', name: 'TRUNC', category: 'Math & Trig',
    syntax: '=TRUNC(number, [num_digits])',
    description: "Cuts off the decimal part of a number without rounding." },
  { id: 'ceiling', name: 'CEILING', category: 'Math & Trig',
    syntax: '=CEILING(number, significance)',
    description: "Rounds a number up to the nearest multiple of a chosen value." },
  { id: 'floor', name: 'FLOOR', category: 'Math & Trig',
    syntax: '=FLOOR(number, significance)',
    description: "Rounds a number down to the nearest multiple of a chosen value." },
  { id: 'product', name: 'PRODUCT', category: 'Math & Trig',
    syntax: '=PRODUCT(number1, [number2], ...)',
    description: "Multiplies all the given numbers together." },
  { id: 'rand', name: 'RAND', category: 'Math & Trig',
    syntax: '=RAND()',
    description: "Returns a random decimal number between 0 and 1." },
  { id: 'randbetween', name: 'RANDBETWEEN', category: 'Math & Trig',
    syntax: '=RANDBETWEEN(bottom, top)',
    description: "Returns a random whole number between two values." },
  { id: 'pi', name: 'PI', category: 'Math & Trig',
    syntax: '=PI()',
    description: "Returns the value of pi." },
  { id: 'gcd', name: 'GCD', category: 'Math & Trig',
    syntax: '=GCD(number1, [number2], ...)',
    description: "Returns the greatest common divisor of a set of numbers." },
  { id: 'lcm', name: 'LCM', category: 'Math & Trig',
    syntax: '=LCM(number1, [number2], ...)',
    description: "Returns the least common multiple of a set of numbers." },
  { id: 'subtotal', name: 'SUBTOTAL', category: 'Math & Trig',
    syntax: '=SUBTOTAL(function_num, ref1, ...)',
    description: "Performs a calculation like SUM or AVERAGE while ignoring other subtotals in the range." },

  // ---------------- Text ----------------
  { id: 'concatenate', name: 'CONCATENATE', category: 'Text',
    syntax: '=CONCATENATE(text1, [text2], ...)',
    description: "Joins several pieces of text into one." },
  { id: 'concat', name: 'CONCAT', category: 'Text',
    syntax: '=CONCAT(text1, [text2], ...)',
    description: "The modern version of CONCATENATE, also works across ranges." },
  { id: 'textjoin', name: 'TEXTJOIN', category: 'Text',
    syntax: '=TEXTJOIN(delimiter, ignore_empty, text1, ...)',
    description: "Joins text together with a chosen separator between each piece." },
  { id: 'left', name: 'LEFT', category: 'Text',
    syntax: '=LEFT(text, [num_chars])',
    description: "Pulls a set number of characters from the start of a text string." },
  { id: 'right', name: 'RIGHT', category: 'Text',
    syntax: '=RIGHT(text, [num_chars])',
    description: "Pulls a set number of characters from the end of a text string." },
  { id: 'mid', name: 'MID', category: 'Text',
    syntax: '=MID(text, start_num, num_chars)',
    description: "Pulls characters from the middle of a text string." },
  { id: 'len', name: 'LEN', category: 'Text',
    syntax: '=LEN(text)',
    description: "Counts how many characters are in a text string." },
  { id: 'trim', name: 'TRIM', category: 'Text',
    syntax: '=TRIM(text)',
    description: "Removes extra spaces from text, leaving single spaces between words." },
  { id: 'upper', name: 'UPPER', category: 'Text',
    syntax: '=UPPER(text)',
    description: "Converts text to all uppercase." },
  { id: 'lower', name: 'LOWER', category: 'Text',
    syntax: '=LOWER(text)',
    description: "Converts text to all lowercase." },
  { id: 'proper', name: 'PROPER', category: 'Text',
    syntax: '=PROPER(text)',
    description: "Capitalizes the first letter of each word." },
  { id: 'substitute', name: 'SUBSTITUTE', category: 'Text',
    syntax: '=SUBSTITUTE(text, old_text, new_text, [instance_num])',
    description: "Replaces specific text within a string." },
  { id: 'replace', name: 'REPLACE', category: 'Text',
    syntax: '=REPLACE(old_text, start_num, num_chars, new_text)',
    description: "Replaces part of a text string based on position, not content." },
  { id: 'find', name: 'FIND', category: 'Text',
    syntax: '=FIND(find_text, within_text, [start_num])',
    description: "Finds the position of text within another string (case-sensitive)." },
  { id: 'search', name: 'SEARCH', category: 'Text',
    syntax: '=SEARCH(find_text, within_text, [start_num])',
    description: "Like FIND, but not case-sensitive and allows wildcards." },
  { id: 'text', name: 'TEXT', category: 'Text',
    syntax: '=TEXT(value, format_text)',
    description: "Converts a number into text, formatted the way you choose." },
  { id: 'value', name: 'VALUE', category: 'Text',
    syntax: '=VALUE(text)',
    description: "Converts text that looks like a number into an actual number." },
  { id: 'exact', name: 'EXACT', category: 'Text',
    syntax: '=EXACT(text1, text2)',
    description: "Checks if two text strings are exactly identical, including case." },
  { id: 'rept', name: 'REPT', category: 'Text',
    syntax: '=REPT(text, number_times)',
    description: "Repeats a piece of text a set number of times." },

  // ---------------- Logic ----------------
  { id: 'if', name: 'IF', category: 'Logic',
    syntax: '=IF(logical_test, value_if_true, value_if_false)',
    description: "Returns one value if a condition is true, another if false.",
    params: [['logical_test','The condition to check, e.g. B2>=40'],['value_if_true','Result if true'],['value_if_false','Result if false']],
    useCase: "Flagging an employee as Pass or Fail based on a score cutoff." },
  { id: 'ifs', name: 'IFS', category: 'Logic',
    syntax: '=IFS(logical_test1, value1, [logical_test2, value2], ...)',
    description: "Checks multiple conditions in order and returns the value for the first one that's true." },
  { id: 'and', name: 'AND', category: 'Logic',
    syntax: '=AND(logical1, [logical2], ...)',
    description: "Returns TRUE only if every condition given is true." },
  { id: 'or', name: 'OR', category: 'Logic',
    syntax: '=OR(logical1, [logical2], ...)',
    description: "Returns TRUE if at least one condition given is true." },
  { id: 'not', name: 'NOT', category: 'Logic',
    syntax: '=NOT(logical)',
    description: "Flips TRUE to FALSE and FALSE to TRUE." },
  { id: 'xor', name: 'XOR', category: 'Logic',
    syntax: '=XOR(logical1, [logical2], ...)',
    description: "Returns TRUE if an odd number of the given conditions are true." },
  { id: 'iferror', name: 'IFERROR', category: 'Logic',
    syntax: '=IFERROR(value, value_if_error)',
    description: "Runs a formula, but shows a fallback value instead of an error if it fails." },
  { id: 'ifna', name: 'IFNA', category: 'Logic',
    syntax: '=IFNA(value, value_if_na)',
    description: "Like IFERROR, but only catches #N/A errors specifically." },
  { id: 'switch', name: 'SWITCH', category: 'Logic',
    syntax: '=SWITCH(expression, value1, result1, [default])',
    description: "Compares one value against a list of options and returns a matching result." },

  // ---------------- Date & Time ----------------
  { id: 'today', name: 'TODAY', category: 'Date & Time',
    syntax: '=TODAY()',
    description: "Returns today's date, updated automatically." },
  { id: 'now', name: 'NOW', category: 'Date & Time',
    syntax: '=NOW()',
    description: "Returns the current date and time." },
  { id: 'date', name: 'DATE', category: 'Date & Time',
    syntax: '=DATE(year, month, day)',
    description: "Builds a real date value from separate year, month, and day numbers." },
  { id: 'datedif', name: 'DATEDIF', category: 'Date & Time',
    syntax: '=DATEDIF(start_date, end_date, unit)',
    description: "Calculates the difference between two dates in days, months, or years." },
  { id: 'day', name: 'DAY', category: 'Date & Time',
    syntax: '=DAY(serial_number)',
    description: "Pulls just the day number out of a date." },
  { id: 'month', name: 'MONTH', category: 'Date & Time',
    syntax: '=MONTH(serial_number)',
    description: "Pulls just the month number out of a date." },
  { id: 'year', name: 'YEAR', category: 'Date & Time',
    syntax: '=YEAR(serial_number)',
    description: "Pulls just the year out of a date." },
  { id: 'weekday', name: 'WEEKDAY', category: 'Date & Time',
    syntax: '=WEEKDAY(serial_number, [return_type])',
    description: "Returns which day of the week a date falls on, as a number." },
  { id: 'weeknum', name: 'WEEKNUM', category: 'Date & Time',
    syntax: '=WEEKNUM(serial_number, [return_type])',
    description: "Returns which week of the year a date falls in." },
  { id: 'eomonth', name: 'EOMONTH', category: 'Date & Time',
    syntax: '=EOMONTH(start_date, months)',
    description: "Returns the last day of the month, a set number of months away." },
  { id: 'edate', name: 'EDATE', category: 'Date & Time',
    syntax: '=EDATE(start_date, months)',
    description: "Returns a date a set number of months before or after a start date." },
  { id: 'networkdays', name: 'NETWORKDAYS', category: 'Date & Time',
    syntax: '=NETWORKDAYS(start_date, end_date, [holidays])',
    description: "Counts working days between two dates, excluding weekends." },
  { id: 'workday', name: 'WORKDAY', category: 'Date & Time',
    syntax: '=WORKDAY(start_date, days, [holidays])',
    description: "Returns the date a set number of working days from a start date." },
  { id: 'time', name: 'TIME', category: 'Date & Time',
    syntax: '=TIME(hour, minute, second)',
    description: "Builds a time value from separate hour, minute, and second numbers." },
  { id: 'hour', name: 'HOUR', category: 'Date & Time',
    syntax: '=HOUR(serial_number)',
    description: "Pulls just the hour out of a time value." },

  // ---------------- Statistical ----------------
  { id: 'count', name: 'COUNT', category: 'Statistical',
    syntax: '=COUNT(value1, [value2], ...)',
    description: "Counts how many cells in a range contain numbers." },
  { id: 'counta', name: 'COUNTA', category: 'Statistical',
    syntax: '=COUNTA(value1, [value2], ...)',
    description: "Counts how many cells in a range are not empty." },
  { id: 'countblank', name: 'COUNTBLANK', category: 'Statistical',
    syntax: '=COUNTBLANK(range)',
    description: "Counts how many cells in a range are empty." },
  { id: 'countif', name: 'COUNTIF', category: 'Statistical',
    syntax: '=COUNTIF(range, criteria)',
    description: "Counts how many cells in a range match a condition.",
    params: [['range','Cells to check'],['criteria','Condition to match, e.g. "Finance"']],
    useCase: "Counting how many employees belong to one department." },
  { id: 'countifs', name: 'COUNTIFS', category: 'Statistical',
    syntax: '=COUNTIFS(criteria_range1, criteria1, ...)',
    description: "Like COUNTIF, but can check multiple conditions at once." },
  { id: 'max', name: 'MAX', category: 'Statistical',
    syntax: '=MAX(number1, [number2], ...)',
    description: "Returns the largest number in a set." },
  { id: 'min', name: 'MIN', category: 'Statistical',
    syntax: '=MIN(number1, [number2], ...)',
    description: "Returns the smallest number in a set." },
  { id: 'maxifs', name: 'MAXIFS', category: 'Statistical',
    syntax: '=MAXIFS(max_range, criteria_range1, criteria1, ...)',
    description: "Returns the largest number in a range that meets given conditions." },
  { id: 'minifs', name: 'MINIFS', category: 'Statistical',
    syntax: '=MINIFS(min_range, criteria_range1, criteria1, ...)',
    description: "Returns the smallest number in a range that meets given conditions." },
  { id: 'median', name: 'MEDIAN', category: 'Statistical',
    syntax: '=MEDIAN(number1, [number2], ...)',
    description: "Returns the middle value in a set of numbers." },
  { id: 'mode', name: 'MODE', category: 'Statistical',
    syntax: '=MODE(number1, [number2], ...)',
    description: "Returns the most frequently occurring number in a set." },
  { id: 'stdev', name: 'STDEV', category: 'Statistical',
    syntax: '=STDEV(number1, [number2], ...)',
    description: "Measures how spread out a set of numbers is from the average." },
  { id: 'var', name: 'VAR', category: 'Statistical',
    syntax: '=VAR(number1, [number2], ...)',
    description: "Measures the variance of a set of numbers." },
  { id: 'rank', name: 'RANK', category: 'Statistical',
    syntax: '=RANK(number, ref, [order])',
    description: "Returns the rank of a number within a list of numbers." },
  { id: 'large', name: 'LARGE', category: 'Statistical',
    syntax: '=LARGE(array, k)',
    description: "Returns the k-th largest value in a set — e.g. the 2nd biggest sale." },
  { id: 'small', name: 'SMALL', category: 'Statistical',
    syntax: '=SMALL(array, k)',
    description: "Returns the k-th smallest value in a set." },

  // ---------------- Financial ----------------
  { id: 'pmt', name: 'PMT', category: 'Financial',
    syntax: '=PMT(rate, nper, pv, [fv], [type])',
    description: "Calculates the fixed periodic payment for a loan." },
  { id: 'fv', name: 'FV', category: 'Financial',
    syntax: '=FV(rate, nper, pmt, [pv], [type])',
    description: "Calculates the future value of an investment based on regular payments." },
  { id: 'pv', name: 'PV', category: 'Financial',
    syntax: '=PV(rate, nper, pmt, [fv], [type])',
    description: "Calculates the present value of a series of future payments." },
  { id: 'npv', name: 'NPV', category: 'Financial',
    syntax: '=NPV(rate, value1, [value2], ...)',
    description: "Calculates the net present value of a series of cash flows." },
  { id: 'irr', name: 'IRR', category: 'Financial',
    syntax: '=IRR(values, [guess])',
    description: "Estimates the internal rate of return for a series of cash flows." },
  { id: 'rate', name: 'RATE', category: 'Financial',
    syntax: '=RATE(nper, pmt, pv, [fv], [type])',
    description: "Calculates the interest rate per period for a loan or investment." },
  { id: 'nper', name: 'NPER', category: 'Financial',
    syntax: '=NPER(rate, pmt, pv, [fv], [type])',
    description: "Calculates how many payment periods are needed to pay off a loan." },

  // ---------------- Information ----------------
  { id: 'isblank', name: 'ISBLANK', category: 'Information',
    syntax: '=ISBLANK(value)',
    description: "Checks whether a cell is empty." },
  { id: 'iserror', name: 'ISERROR', category: 'Information',
    syntax: '=ISERROR(value)',
    description: "Checks whether a value is any kind of error." },
  { id: 'isnumber', name: 'ISNUMBER', category: 'Information',
    syntax: '=ISNUMBER(value)',
    description: "Checks whether a value is a number." },
  { id: 'istext', name: 'ISTEXT', category: 'Information',
    syntax: '=ISTEXT(value)',
    description: "Checks whether a value is text." },
  { id: 'isna', name: 'ISNA', category: 'Information',
    syntax: '=ISNA(value)',
    description: "Checks whether a value is the #N/A error specifically." },
  { id: 'iseven', name: 'ISEVEN', category: 'Information',
    syntax: '=ISEVEN(number)',
    description: "Checks whether a number is even." },
  { id: 'isodd', name: 'ISODD', category: 'Information',
    syntax: '=ISODD(number)',
    description: "Checks whether a number is odd." },

  { id: 'sin', name: 'SIN', category: 'Math & Trig',
    syntax: '=SIN(number)',
    description: "Returns the sine of an angle given in radians." },
  { id: 'cos', name: 'COS', category: 'Math & Trig',
    syntax: '=COS(number)',
    description: "Returns the cosine of an angle given in radians." },
  { id: 'tan', name: 'TAN', category: 'Math & Trig',
    syntax: '=TAN(number)',
    description: "Returns the tangent of an angle given in radians." },
  { id: 'asin', name: 'ASIN', category: 'Math & Trig',
    syntax: '=ASIN(number)',
    description: "Returns the arcsine of a number, in radians." },
  { id: 'acos', name: 'ACOS', category: 'Math & Trig',
    syntax: '=ACOS(number)',
    description: "Returns the arccosine of a number, in radians." },
  { id: 'atan', name: 'ATAN', category: 'Math & Trig',
    syntax: '=ATAN(number)',
    description: "Returns the arctangent of a number, in radians." },
  { id: 'atan2', name: 'ATAN2', category: 'Math & Trig',
    syntax: '=ATAN2(x_num, y_num)',
    description: "Returns the arctangent from x and y coordinates." },
  { id: 'sinh', name: 'SINH', category: 'Math & Trig',
    syntax: '=SINH(number)',
    description: "Returns the hyperbolic sine of a number." },
  { id: 'cosh', name: 'COSH', category: 'Math & Trig',
    syntax: '=COSH(number)',
    description: "Returns the hyperbolic cosine of a number." },
  { id: 'tanh', name: 'TANH', category: 'Math & Trig',
    syntax: '=TANH(number)',
    description: "Returns the hyperbolic tangent of a number." },
  { id: 'degrees', name: 'DEGREES', category: 'Math & Trig',
    syntax: '=DEGREES(angle)',
    description: "Converts an angle from radians to degrees." },
  { id: 'radians', name: 'RADIANS', category: 'Math & Trig',
    syntax: '=RADIANS(angle)',
    description: "Converts an angle from degrees to radians." },
  { id: 'exp', name: 'EXP', category: 'Math & Trig',
    syntax: '=EXP(number)',
    description: "Returns e raised to the power of a given number." },
  { id: 'ln', name: 'LN', category: 'Math & Trig',
    syntax: '=LN(number)',
    description: "Returns the natural logarithm of a number." },
  { id: 'log', name: 'LOG', category: 'Math & Trig',
    syntax: '=LOG(number, [base])',
    description: "Returns the logarithm of a number to a base you specify." },
  { id: 'log10', name: 'LOG10', category: 'Math & Trig',
    syntax: '=LOG10(number)',
    description: "Returns the base-10 logarithm of a number." },
  { id: 'sqrtpi', name: 'SQRTPI', category: 'Math & Trig',
    syntax: '=SQRTPI(number)',
    description: "Returns the square root of a number multiplied by pi." },
  { id: 'fact', name: 'FACT', category: 'Math & Trig',
    syntax: '=FACT(number)',
    description: "Returns the factorial of a number." },
  { id: 'factdouble', name: 'FACTDOUBLE', category: 'Math & Trig',
    syntax: '=FACTDOUBLE(number)',
    description: "Returns the double factorial of a number." },
  { id: 'multinomial', name: 'MULTINOMIAL', category: 'Math & Trig',
    syntax: '=MULTINOMIAL(number1, [number2], ...)',
    description: "Returns the ratio of the factorial of a sum to the product of factorials." },
  { id: 'mdeterm', name: 'MDETERM', category: 'Math & Trig',
    syntax: '=MDETERM(array)',
    description: "Returns the matrix determinant of an array." },
  { id: 'mmult', name: 'MMULT', category: 'Math & Trig',
    syntax: '=MMULT(array1, array2)',
    description: "Returns the matrix product of two arrays." },
  { id: 'minverse', name: 'MINVERSE', category: 'Math & Trig',
    syntax: '=MINVERSE(array)',
    description: "Returns the inverse of a matrix stored in an array." },
  { id: 'munit', name: 'MUNIT', category: 'Math & Trig',
    syntax: '=MUNIT(dimension)',
    description: "Returns the identity matrix for a given dimension." },
  { id: 'sumsq', name: 'SUMSQ', category: 'Math & Trig',
    syntax: '=SUMSQ(number1, [number2], ...)',
    description: "Returns the sum of the squares of the given values." },
  { id: 'sumx2my2', name: 'SUMX2MY2', category: 'Math & Trig',
    syntax: '=SUMX2MY2(array_x, array_y)',
    description: "Sums the difference of squares of two corresponding ranges." },
  { id: 'sumx2py2', name: 'SUMX2PY2', category: 'Math & Trig',
    syntax: '=SUMX2PY2(array_x, array_y)',
    description: "Sums the total of squares of two corresponding ranges." },
  { id: 'sumxmy2', name: 'SUMXMY2', category: 'Math & Trig',
    syntax: '=SUMXMY2(array_x, array_y)',
    description: "Sums the squares of differences between two corresponding ranges." },
  { id: 'sign', name: 'SIGN', category: 'Math & Trig',
    syntax: '=SIGN(number)',
    description: "Returns 1, 0, or -1 depending on whether a number is positive, zero, or negative." },
  { id: 'odd', name: 'ODD', category: 'Math & Trig',
    syntax: '=ODD(number)',
    description: "Rounds a number up to the nearest odd integer." },
  { id: 'even', name: 'EVEN', category: 'Math & Trig',
    syntax: '=EVEN(number)',
    description: "Rounds a number up to the nearest even integer." },
  { id: 'ceilingmath', name: 'CEILING.MATH', category: 'Math & Trig',
    syntax: '=CEILING.MATH(number, [significance], [mode])',
    description: "Rounds a number up to the nearest multiple, with directional control for negatives." },
  { id: 'floormath', name: 'FLOOR.MATH', category: 'Math & Trig',
    syntax: '=FLOOR.MATH(number, [significance], [mode])',
    description: "Rounds a number down to the nearest multiple, with directional control for negatives." },
  { id: 'ceilingprecise', name: 'CEILING.PRECISE', category: 'Math & Trig',
    syntax: '=CEILING.PRECISE(number, [significance])',
    description: "Rounds a number up to the nearest multiple, always rounding away from zero." },
  { id: 'floorprecise', name: 'FLOOR.PRECISE', category: 'Math & Trig',
    syntax: '=FLOOR.PRECISE(number, [significance])',
    description: "Rounds a number down to the nearest multiple, always rounding toward zero." },
  { id: 'isoceiling', name: 'ISO.CEILING', category: 'Math & Trig',
    syntax: '=ISO.CEILING(number, [significance])',
    description: "Rounds a number up to the nearest multiple, following ISO rules." },
  { id: 'quotient', name: 'QUOTIENT', category: 'Math & Trig',
    syntax: '=QUOTIENT(numerator, denominator)',
    description: "Returns the integer portion of a division." },
  { id: 'seriessum', name: 'SERIESSUM', category: 'Math & Trig',
    syntax: '=SERIESSUM(x, n, m, coefficients)',
    description: "Returns the sum of a power series based on a formula." },
  { id: 'sequence', name: 'SEQUENCE', category: 'Math & Trig',
    syntax: '=SEQUENCE(rows, [columns], [start], [step])',
    description: "Generates a list of sequential numbers in an array." },
  { id: 'randarray', name: 'RANDARRAY', category: 'Math & Trig',
    syntax: '=RANDARRAY([rows], [columns], [min], [max], [whole_number])',
    description: "Returns an array of random numbers." },
  { id: 'arabic', name: 'ARABIC', category: 'Math & Trig',
    syntax: '=ARABIC(text)',
    description: "Converts a Roman numeral to an Arabic (regular) number." },
  { id: 'roman', name: 'ROMAN', category: 'Math & Trig',
    syntax: '=ROMAN(number, [form])',
    description: "Converts a number to a Roman numeral, as text." },
  { id: 'base', name: 'BASE', category: 'Math & Trig',
    syntax: '=BASE(number, radix, [min_length])',
    description: "Converts a number into a text representation in another base." },
  { id: 'decimal', name: 'DECIMAL', category: 'Math & Trig',
    syntax: '=DECIMAL(text, radix)',
    description: "Converts a text representation of a number in another base to decimal." },
  { id: 'textbefore', name: 'TEXTBEFORE', category: 'Text',
    syntax: '=TEXTBEFORE(text, delimiter)',
    description: "Returns the text that occurs before a given delimiter." },
  { id: 'textafter', name: 'TEXTAFTER', category: 'Text',
    syntax: '=TEXTAFTER(text, delimiter)',
    description: "Returns the text that occurs after a given delimiter." },
  { id: 'textsplit', name: 'TEXTSPLIT', category: 'Text',
    syntax: '=TEXTSPLIT(text, col_delimiter, [row_delimiter])',
    description: "Splits text into rows or columns using delimiters." },
  { id: 'arraytotext', name: 'ARRAYTOTEXT', category: 'Text',
    syntax: '=ARRAYTOTEXT(array, [format])',
    description: "Returns an array of text values from any range, joined together." },
  { id: 'valuetotext', name: 'VALUETOTEXT', category: 'Text',
    syntax: '=VALUETOTEXT(value, [format])',
    description: "Returns text from any single value." },
  { id: 'numbervalue', name: 'NUMBERVALUE', category: 'Text',
    syntax: '=NUMBERVALUE(text, [decimal_separator], [group_separator])',
    description: "Converts text to a number in a locale-independent way." },
  { id: 'dollar', name: 'DOLLAR', category: 'Text',
    syntax: '=DOLLAR(number, [decimals])',
    description: "Converts a number to text using currency format." },
  { id: 'fixed', name: 'FIXED', category: 'Text',
    syntax: '=FIXED(number, [decimals], [no_commas])',
    description: "Rounds a number and converts it to text with a fixed number of decimals." },
  { id: 't', name: 'T', category: 'Text',
    syntax: '=T(value)',
    description: "Returns the text referred to by a value, or an empty string if it isn't text." },
  { id: 'clean', name: 'CLEAN', category: 'Text',
    syntax: '=CLEAN(text)',
    description: "Removes non-printable characters from text." },
  { id: 'unichar', name: 'UNICHAR', category: 'Text',
    syntax: '=UNICHAR(number)',
    description: "Returns the Unicode character for a given number." },
  { id: 'unicode', name: 'UNICODE', category: 'Text',
    syntax: '=UNICODE(text)',
    description: "Returns the Unicode number for the first character of text." },
  { id: 'asc', name: 'ASC', category: 'Text',
    syntax: '=ASC(text)',
    description: "Converts full-width characters to half-width characters." },
  { id: 'bahttext', name: 'BAHTTEXT', category: 'Text',
    syntax: '=BAHTTEXT(number)',
    description: "Converts a number to Thai text with a currency suffix." },
  { id: 'isoweeknum', name: 'ISOWEEKNUM', category: 'Date & Time',
    syntax: '=ISOWEEKNUM(date)',
    description: "Returns the ISO week number of the year for a date." },
  { id: 'datevalue', name: 'DATEVALUE', category: 'Date & Time',
    syntax: '=DATEVALUE(date_text)',
    description: "Converts a date stored as text into a real date value." },
  { id: 'timevalue', name: 'TIMEVALUE', category: 'Date & Time',
    syntax: '=TIMEVALUE(time_text)',
    description: "Converts a time stored as text into a real time value." },
  { id: 'days', name: 'DAYS', category: 'Date & Time',
    syntax: '=DAYS(end_date, start_date)',
    description: "Returns the number of days between two dates." },
  { id: 'days360', name: 'DAYS360', category: 'Date & Time',
    syntax: '=DAYS360(start_date, end_date, [method])',
    description: "Returns days between two dates based on a 360-day year." },
  { id: 'yearfrac', name: 'YEARFRAC', category: 'Date & Time',
    syntax: '=YEARFRAC(start_date, end_date, [basis])',
    description: "Returns the fraction of a year between two dates." },
  { id: 'networkdaysintl', name: 'NETWORKDAYS.INTL', category: 'Date & Time',
    syntax: '=NETWORKDAYS.INTL(start_date, end_date, [weekend], [holidays])',
    description: "Counts working days between two dates with a custom weekend." },
  { id: 'workdayintl', name: 'WORKDAY.INTL', category: 'Date & Time',
    syntax: '=WORKDAY.INTL(start_date, days, [weekend], [holidays])',
    description: "Returns a future/past workday with a custom weekend." },
  { id: 'minute', name: 'MINUTE', category: 'Date & Time',
    syntax: '=MINUTE(serial_number)',
    description: "Pulls just the minute out of a time value." },
  { id: 'second', name: 'SECOND', category: 'Date & Time',
    syntax: '=SECOND(serial_number)',
    description: "Pulls just the second out of a time value." },
  { id: 'hyperlink', name: 'HYPERLINK', category: 'Lookup & Reference',
    syntax: '=HYPERLINK(link_location, [friendly_name])',
    description: "Creates a clickable shortcut that jumps to another location." },
  { id: 'getpivotdata', name: 'GETPIVOTDATA', category: 'Lookup & Reference',
    syntax: '=GETPIVOTDATA(data_field, pivot_table, [field1, item1], ...)',
    description: "Pulls a specific value out of a PivotTable." },
  { id: 'areas', name: 'AREAS', category: 'Lookup & Reference',
    syntax: '=AREAS(reference)',
    description: "Returns the number of separate areas in a reference." },
  { id: 'formulatext', name: 'FORMULATEXT', category: 'Lookup & Reference',
    syntax: '=FORMULATEXT(reference)',
    description: "Returns a formula as text, so you can see it displayed in another cell." },
  { id: 'xmatch', name: 'XMATCH', category: 'Lookup & Reference',
    syntax: '=XMATCH(lookup_value, lookup_array, [match_mode], [search_mode])',
    description: "The modern replacement for MATCH \u2014 more flexible matching and search options." },
  { id: 'take', name: 'TAKE', category: 'Lookup & Reference',
    syntax: '=TAKE(array, rows, [columns])',
    description: "Returns a set number of rows or columns from the start or end of an array." },
  { id: 'drop', name: 'DROP', category: 'Lookup & Reference',
    syntax: '=DROP(array, rows, [columns])',
    description: "Excludes a set number of rows or columns from an array." },
  { id: 'expand', name: 'EXPAND', category: 'Lookup & Reference',
    syntax: '=EXPAND(array, rows, [columns], [pad_with])',
    description: "Expands an array to a specified size, padding with a chosen value." },
  { id: 'hstack', name: 'HSTACK', category: 'Lookup & Reference',
    syntax: '=HSTACK(array1, [array2], ...)',
    description: "Combines arrays side by side into one array." },
  { id: 'vstack', name: 'VSTACK', category: 'Lookup & Reference',
    syntax: '=VSTACK(array1, [array2], ...)',
    description: "Combines arrays on top of each other into one array." },
  { id: 'tocol', name: 'TOCOL', category: 'Lookup & Reference',
    syntax: '=TOCOL(array, [ignore], [scan_by_column])',
    description: "Returns an array as a single column." },
  { id: 'torow', name: 'TOROW', category: 'Lookup & Reference',
    syntax: '=TOROW(array, [ignore], [scan_by_column])',
    description: "Returns an array as a single row." },
  { id: 'chooserows', name: 'CHOOSEROWS', category: 'Lookup & Reference',
    syntax: '=CHOOSEROWS(array, row_num1, ...)',
    description: "Returns specific rows from an array by their position." },
  { id: 'choosecols', name: 'CHOOSECOLS', category: 'Lookup & Reference',
    syntax: '=CHOOSECOLS(array, col_num1, ...)',
    description: "Returns specific columns from an array by their position." },
  { id: 'normdist2', name: 'NORM.DIST', category: 'Statistical',
    syntax: '=NORM.DIST(x, mean, standard_dev, cumulative)',
    description: "Returns the normal distribution for a given mean and standard deviation." },
  { id: 'norminv2', name: 'NORM.INV', category: 'Statistical',
    syntax: '=NORM.INV(probability, mean, standard_dev)',
    description: "Returns the inverse of the normal cumulative distribution." },
  { id: 'normsdist2', name: 'NORM.S.DIST', category: 'Statistical',
    syntax: '=NORM.S.DIST(z, cumulative)',
    description: "Returns the standard normal distribution." },
  { id: 'normsinv2', name: 'NORM.S.INV', category: 'Statistical',
    syntax: '=NORM.S.INV(probability)',
    description: "Returns the inverse of the standard normal distribution." },
  { id: 'tdist2', name: 'T.DIST', category: 'Statistical',
    syntax: '=T.DIST(x, deg_freedom, cumulative)',
    description: "Returns the Student's t-distribution." },
  { id: 'tinv2', name: 'T.INV', category: 'Statistical',
    syntax: '=T.INV(probability, deg_freedom)',
    description: "Returns the inverse of the Student's t-distribution." },
  { id: 'chisqdist', name: 'CHISQ.DIST', category: 'Statistical',
    syntax: '=CHISQ.DIST(x, deg_freedom, cumulative)',
    description: "Returns the chi-squared distribution." },
  { id: 'chisqinv', name: 'CHISQ.INV', category: 'Statistical',
    syntax: '=CHISQ.INV(probability, deg_freedom)',
    description: "Returns the inverse of the chi-squared distribution." },
  { id: 'fdist2', name: 'F.DIST', category: 'Statistical',
    syntax: '=F.DIST(x, deg_freedom1, deg_freedom2, cumulative)',
    description: "Returns the F probability distribution." },
  { id: 'finv2', name: 'F.INV', category: 'Statistical',
    syntax: '=F.INV(probability, deg_freedom1, deg_freedom2)',
    description: "Returns the inverse of the F probability distribution." },
  { id: 'betadist2', name: 'BETA.DIST', category: 'Statistical',
    syntax: '=BETA.DIST(x, alpha, beta, cumulative, [A], [B])',
    description: "Returns the beta distribution." },
  { id: 'betainv2', name: 'BETA.INV', category: 'Statistical',
    syntax: '=BETA.INV(probability, alpha, beta, [A], [B])',
    description: "Returns the inverse of the beta distribution." },
  { id: 'gammadist2', name: 'GAMMA.DIST', category: 'Statistical',
    syntax: '=GAMMA.DIST(x, alpha, beta, cumulative)',
    description: "Returns the gamma distribution." },
  { id: 'gammainv2', name: 'GAMMA.INV', category: 'Statistical',
    syntax: '=GAMMA.INV(probability, alpha, beta)',
    description: "Returns the inverse of the gamma cumulative distribution." },
  { id: 'binomdist2', name: 'BINOM.DIST', category: 'Statistical',
    syntax: '=BINOM.DIST(number_s, trials, probability_s, cumulative)',
    description: "Returns the individual term binomial distribution probability." },
  { id: 'binominv', name: 'BINOM.INV', category: 'Statistical',
    syntax: '=BINOM.INV(trials, probability_s, alpha)',
    description: "Returns the smallest value where the binomial distribution is >= a criterion." },
  { id: 'poissondist2', name: 'POISSON.DIST', category: 'Statistical',
    syntax: '=POISSON.DIST(x, mean, cumulative)',
    description: "Returns the Poisson distribution." },
  { id: 'weibulldist2', name: 'WEIBULL.DIST', category: 'Statistical',
    syntax: '=WEIBULL.DIST(x, alpha, beta, cumulative)',
    description: "Returns the Weibull distribution." },
  { id: 'expondist2', name: 'EXPON.DIST', category: 'Statistical',
    syntax: '=EXPON.DIST(x, lambda, cumulative)',
    description: "Returns the exponential distribution." },
  { id: 'hypgeomdist2', name: 'HYPGEOM.DIST', category: 'Statistical',
    syntax: '=HYPGEOM.DIST(sample_s, number_sample, population_s, number_pop, cumulative)',
    description: "Returns the hypergeometric distribution." },
  { id: 'lognormdist2', name: 'LOGNORM.DIST', category: 'Statistical',
    syntax: '=LOGNORM.DIST(x, mean, standard_dev, cumulative)',
    description: "Returns the lognormal distribution." },
  { id: 'lognorminv2', name: 'LOGNORM.INV', category: 'Statistical',
    syntax: '=LOGNORM.INV(probability, mean, standard_dev)',
    description: "Returns the inverse of the lognormal distribution." },
  { id: 'negbinomdist2', name: 'NEGBINOM.DIST', category: 'Statistical',
    syntax: '=NEGBINOM.DIST(number_f, number_s, probability_s, cumulative)',
    description: "Returns the negative binomial distribution." },
  { id: 'confidencenorm', name: 'CONFIDENCE.NORM', category: 'Statistical',
    syntax: '=CONFIDENCE.NORM(alpha, standard_dev, size)',
    description: "Returns the confidence interval for a population mean using a normal distribution." },
  { id: 'confidencet', name: 'CONFIDENCE.T', category: 'Statistical',
    syntax: '=CONFIDENCE.T(alpha, standard_dev, size)',
    description: "Returns the confidence interval for a population mean using a Student's t-distribution." },
  { id: 'percentileinc', name: 'PERCENTILE.INC', category: 'Statistical',
    syntax: '=PERCENTILE.INC(array, k)',
    description: "Returns the k-th percentile of values in a range, inclusive." },
  { id: 'percentileexc', name: 'PERCENTILE.EXC', category: 'Statistical',
    syntax: '=PERCENTILE.EXC(array, k)',
    description: "Returns the k-th percentile of values in a range, exclusive." },
  { id: 'quartileinc', name: 'QUARTILE.INC', category: 'Statistical',
    syntax: '=QUARTILE.INC(array, quart)',
    description: "Returns the quartile of a data set, inclusive." },
  { id: 'quartileexc', name: 'QUARTILE.EXC', category: 'Statistical',
    syntax: '=QUARTILE.EXC(array, quart)',
    description: "Returns the quartile of a data set, exclusive." },
  { id: 'rankeq', name: 'RANK.EQ', category: 'Statistical',
    syntax: '=RANK.EQ(number, ref, [order])',
    description: "Returns the rank of a number, giving equal values the same top rank." },
  { id: 'rankavg', name: 'RANK.AVG', category: 'Statistical',
    syntax: '=RANK.AVG(number, ref, [order])',
    description: "Returns the rank of a number, averaging the rank for equal values." },
  { id: 'stdevs', name: 'STDEV.S', category: 'Statistical',
    syntax: '=STDEV.S(number1, [number2], ...)',
    description: "Estimates standard deviation based on a sample." },
  { id: 'stdevp2', name: 'STDEV.P', category: 'Statistical',
    syntax: '=STDEV.P(number1, [number2], ...)',
    description: "Calculates standard deviation based on an entire population." },
  { id: 'vars', name: 'VAR.S', category: 'Statistical',
    syntax: '=VAR.S(number1, [number2], ...)',
    description: "Estimates variance based on a sample." },
  { id: 'varp2', name: 'VAR.P', category: 'Statistical',
    syntax: '=VAR.P(number1, [number2], ...)',
    description: "Calculates variance based on an entire population." },
  { id: 'covariancep', name: 'COVARIANCE.P', category: 'Statistical',
    syntax: '=COVARIANCE.P(array1, array2)',
    description: "Returns population covariance between two data sets." },
  { id: 'covariances', name: 'COVARIANCE.S', category: 'Statistical',
    syntax: '=COVARIANCE.S(array1, array2)',
    description: "Returns sample covariance between two data sets." },
  { id: 'correl', name: 'CORREL', category: 'Statistical',
    syntax: '=CORREL(array1, array2)',
    description: "Returns the correlation coefficient between two data sets." },
  { id: 'pearson', name: 'PEARSON', category: 'Statistical',
    syntax: '=PEARSON(array1, array2)',
    description: "Returns the Pearson product-moment correlation coefficient." },
  { id: 'rsq', name: 'RSQ', category: 'Statistical',
    syntax: '=RSQ(known_ys, known_xs)',
    description: "Returns the square of the Pearson correlation coefficient." },
  { id: 'slope', name: 'SLOPE', category: 'Statistical',
    syntax: '=SLOPE(known_ys, known_xs)',
    description: "Returns the slope of a linear regression line." },
  { id: 'intercept', name: 'INTERCEPT', category: 'Statistical',
    syntax: '=INTERCEPT(known_ys, known_xs)',
    description: "Returns the intercept of a linear regression line." },
  { id: 'forecastlinear', name: 'FORECAST.LINEAR', category: 'Statistical',
    syntax: '=FORECAST.LINEAR(x, known_ys, known_xs)',
    description: "Predicts a future value along a linear trend." },
  { id: 'trend', name: 'TREND', category: 'Statistical',
    syntax: '=TREND(known_ys, [known_xs], [new_xs])',
    description: "Returns values along a linear trend line." },
  { id: 'growth', name: 'GROWTH', category: 'Statistical',
    syntax: '=GROWTH(known_ys, [known_xs], [new_xs])',
    description: "Returns values along an exponential growth trend." },
  { id: 'linest', name: 'LINEST', category: 'Statistical',
    syntax: '=LINEST(known_ys, [known_xs])',
    description: "Returns statistics describing a linear regression line." },
  { id: 'logest', name: 'LOGEST', category: 'Statistical',
    syntax: '=LOGEST(known_ys, [known_xs])',
    description: "Returns statistics describing an exponential curve." },
  { id: 'geomean', name: 'GEOMEAN', category: 'Statistical',
    syntax: '=GEOMEAN(number1, [number2], ...)',
    description: "Returns the geometric mean of a set of numbers." },
  { id: 'harmean', name: 'HARMEAN', category: 'Statistical',
    syntax: '=HARMEAN(number1, [number2], ...)',
    description: "Returns the harmonic mean of a set of numbers." },
  { id: 'trimmean', name: 'TRIMMEAN', category: 'Statistical',
    syntax: '=TRIMMEAN(array, percent)',
    description: "Returns the mean of a data set, excluding a percentage from each end." },
  { id: 'skew', name: 'SKEW', category: 'Statistical',
    syntax: '=SKEW(number1, [number2], ...)',
    description: "Returns the skewness of a distribution \u2014 how lopsided it is." },
  { id: 'skewp', name: 'SKEW.P', category: 'Statistical',
    syntax: '=SKEW.P(number1, [number2], ...)',
    description: "Returns the skewness of a distribution based on a population." },
  { id: 'kurt', name: 'KURT', category: 'Statistical',
    syntax: '=KURT(number1, [number2], ...)',
    description: "Returns the kurtosis of a data set \u2014 how peaked or flat it is." },
  { id: 'devsq', name: 'DEVSQ', category: 'Statistical',
    syntax: '=DEVSQ(number1, [number2], ...)',
    description: "Returns the sum of squared deviations from the mean." },
  { id: 'avedev', name: 'AVEDEV', category: 'Statistical',
    syntax: '=AVEDEV(number1, [number2], ...)',
    description: "Returns the average of absolute deviations from the mean." },
  { id: 'modesngl', name: 'MODE.SNGL', category: 'Statistical',
    syntax: '=MODE.SNGL(number1, [number2], ...)',
    description: "Returns the most frequently occurring value in a data set." },
  { id: 'modemult', name: 'MODE.MULT', category: 'Statistical',
    syntax: '=MODE.MULT(number1, [number2], ...)',
    description: "Returns an array of the most frequently occurring values." },
  { id: 'frequency', name: 'FREQUENCY', category: 'Statistical',
    syntax: '=FREQUENCY(data_array, bins_array)',
    description: "Shows how often values occur within ranges (bins)." },
  { id: 'permut', name: 'PERMUT', category: 'Statistical',
    syntax: '=PERMUT(number, number_chosen)',
    description: "Returns the number of permutations for a set of objects." },
  { id: 'permutationa', name: 'PERMUTATIONA', category: 'Statistical',
    syntax: '=PERMUTATIONA(number, number_chosen)',
    description: "Returns the number of permutations, allowing repeats." },
  { id: 'combin', name: 'COMBIN', category: 'Statistical',
    syntax: '=COMBIN(number, number_chosen)',
    description: "Returns the number of combinations for a set of objects." },
  { id: 'combina', name: 'COMBINA', category: 'Statistical',
    syntax: '=COMBINA(number, number_chosen)',
    description: "Returns the number of combinations, allowing repeats." },
  { id: 'fisher', name: 'FISHER', category: 'Statistical',
    syntax: '=FISHER(x)',
    description: "Returns the Fisher transformation." },
  { id: 'fisherinv', name: 'FISHERINV', category: 'Statistical',
    syntax: '=FISHERINV(y)',
    description: "Returns the inverse of the Fisher transformation." },
  { id: 'standardize', name: 'STANDARDIZE', category: 'Statistical',
    syntax: '=STANDARDIZE(x, mean, standard_dev)',
    description: "Returns a normalized (z-score) value." },
  { id: 'prob', name: 'PROB', category: 'Statistical',
    syntax: '=PROB(x_range, prob_range, lower_limit, [upper_limit])',
    description: "Returns the probability that values fall within a range." },
  { id: 'chisqtest', name: 'CHISQ.TEST', category: 'Statistical',
    syntax: '=CHISQ.TEST(actual_range, expected_range)',
    description: "Returns the chi-squared test for independence." },
  { id: 'ttest2', name: 'T.TEST', category: 'Statistical',
    syntax: '=T.TEST(array1, array2, tails, type)',
    description: "Returns the probability from a Student's t-test." },
  { id: 'ftest2', name: 'F.TEST', category: 'Statistical',
    syntax: '=F.TEST(array1, array2)',
    description: "Returns the result of an F-test comparing variances." },
  { id: 'ztest2', name: 'Z.TEST', category: 'Statistical',
    syntax: '=Z.TEST(array, x, [sigma])',
    description: "Returns the one-tailed probability of a z-test." },
  { id: 'ipmt', name: 'IPMT', category: 'Financial',
    syntax: '=IPMT(rate, per, nper, pv, [fv], [type])',
    description: "Returns the interest portion of a loan payment for a given period." },
  { id: 'ppmt', name: 'PPMT', category: 'Financial',
    syntax: '=PPMT(rate, per, nper, pv, [fv], [type])',
    description: "Returns the principal portion of a loan payment for a given period." },
  { id: 'cumipmt', name: 'CUMIPMT', category: 'Financial',
    syntax: '=CUMIPMT(rate, nper, pv, start_period, end_period, type)',
    description: "Returns cumulative interest paid between two periods." },
  { id: 'cumprinc', name: 'CUMPRINC', category: 'Financial',
    syntax: '=CUMPRINC(rate, nper, pv, start_period, end_period, type)',
    description: "Returns cumulative principal paid between two periods." },
  { id: 'syd', name: 'SYD', category: 'Financial',
    syntax: '=SYD(cost, salvage, life, per)',
    description: "Returns sum-of-years' digits depreciation for a period." },
  { id: 'ddb', name: 'DDB', category: 'Financial',
    syntax: '=DDB(cost, salvage, life, period, [factor])',
    description: "Returns depreciation using the double-declining balance method." },
  { id: 'vdb', name: 'VDB', category: 'Financial',
    syntax: '=VDB(cost, salvage, life, start_period, end_period, [factor], [no_switch])',
    description: "Returns depreciation using a variable declining balance method." },
  { id: 'mirr', name: 'MIRR', category: 'Financial',
    syntax: '=MIRR(values, finance_rate, reinvest_rate)',
    description: "Returns the modified internal rate of return for a series of cash flows." },
  { id: 'xnpv', name: 'XNPV', category: 'Financial',
    syntax: '=XNPV(rate, values, dates)',
    description: "Returns net present value for cash flows on irregular dates." },
  { id: 'xirr', name: 'XIRR', category: 'Financial',
    syntax: '=XIRR(values, dates, [guess])',
    description: "Returns internal rate of return for cash flows on irregular dates." },
  { id: 'price', name: 'PRICE', category: 'Financial',
    syntax: '=PRICE(settlement, maturity, rate, yld, redemption, frequency, [basis])',
    description: "Returns the price of a bond per $100 face value." },
  { id: 'yield2', name: 'YIELD', category: 'Financial',
    syntax: '=YIELD(settlement, maturity, rate, pr, redemption, frequency, [basis])',
    description: "Returns the yield on a bond paying periodic interest." },
  { id: 'duration', name: 'DURATION', category: 'Financial',
    syntax: '=DURATION(settlement, maturity, coupon, yld, frequency, [basis])',
    description: "Returns the annual duration of a security with periodic interest." },
  { id: 'mduration', name: 'MDURATION', category: 'Financial',
    syntax: '=MDURATION(settlement, maturity, coupon, yld, frequency, [basis])',
    description: "Returns the modified Macauley duration of a security." },
  { id: 'accrint', name: 'ACCRINT', category: 'Financial',
    syntax: '=ACCRINT(issue, first_interest, settlement, rate, par, frequency, [basis])',
    description: "Returns accrued interest for a security paying periodic interest." },
  { id: 'accrintm', name: 'ACCRINTM', category: 'Financial',
    syntax: '=ACCRINTM(issue, settlement, rate, par, [basis])',
    description: "Returns accrued interest for a security paying interest at maturity." },
  { id: 'disc', name: 'DISC', category: 'Financial',
    syntax: '=DISC(settlement, maturity, pr, redemption, [basis])',
    description: "Returns the discount rate for a security." },
  { id: 'intrate', name: 'INTRATE', category: 'Financial',
    syntax: '=INTRATE(settlement, maturity, investment, redemption, [basis])',
    description: "Returns the interest rate for a fully invested security." },
  { id: 'received', name: 'RECEIVED', category: 'Financial',
    syntax: '=RECEIVED(settlement, maturity, investment, discount, [basis])',
    description: "Returns the amount received at maturity for a fully invested security." },
  { id: 'pricedisc', name: 'PRICEDISC', category: 'Financial',
    syntax: '=PRICEDISC(settlement, maturity, discount, redemption, [basis])',
    description: "Returns the price per $100 face value of a discounted security." },
  { id: 'pricemat', name: 'PRICEMAT', category: 'Financial',
    syntax: '=PRICEMAT(settlement, maturity, issue, rate, yld, [basis])',
    description: "Returns the price per $100 face value of a security paying interest at maturity." },
  { id: 'yielddisc', name: 'YIELDDISC', category: 'Financial',
    syntax: '=YIELDDISC(settlement, maturity, pr, redemption, [basis])',
    description: "Returns the annual yield for a discounted security." },
  { id: 'yieldmat', name: 'YIELDMAT', category: 'Financial',
    syntax: '=YIELDMAT(settlement, maturity, issue, rate, pr, [basis])',
    description: "Returns the annual yield for a security paying interest at maturity." },
  { id: 'tbilleq', name: 'TBILLEQ', category: 'Financial',
    syntax: '=TBILLEQ(settlement, maturity, discount)',
    description: "Returns the bond-equivalent yield for a treasury bill." },
  { id: 'tbillprice', name: 'TBILLPRICE', category: 'Financial',
    syntax: '=TBILLPRICE(settlement, maturity, discount)',
    description: "Returns the price per $100 face value for a treasury bill." },
  { id: 'tbillyield', name: 'TBILLYIELD', category: 'Financial',
    syntax: '=TBILLYIELD(settlement, maturity, pr)',
    description: "Returns the yield for a treasury bill." },
  { id: 'dollarde', name: 'DOLLARDE', category: 'Financial',
    syntax: '=DOLLARDE(fractional_dollar, fraction)',
    description: "Converts a dollar price expressed as a fraction into a decimal." },
  { id: 'dollarfr', name: 'DOLLARFR', category: 'Financial',
    syntax: '=DOLLARFR(decimal_dollar, fraction)',
    description: "Converts a dollar price expressed as a decimal into a fraction." },
  { id: 'effect', name: 'EFFECT', category: 'Financial',
    syntax: '=EFFECT(nominal_rate, npery)',
    description: "Returns the effective annual interest rate from a nominal rate." },
  { id: 'nominal', name: 'NOMINAL', category: 'Financial',
    syntax: '=NOMINAL(effect_rate, npery)',
    description: "Returns the nominal annual interest rate from an effective rate." },
  { id: 'fvschedule', name: 'FVSCHEDULE', category: 'Financial',
    syntax: '=FVSCHEDULE(principal, schedule)',
    description: "Returns the future value of a principal after applying a series of interest rates." },
  { id: 'pduration', name: 'PDURATION', category: 'Financial',
    syntax: '=PDURATION(rate, pv, fv)',
    description: "Returns the number of periods needed for an investment to reach a target value." },
  { id: 'rri', name: 'RRI', category: 'Financial',
    syntax: '=RRI(nper, pv, fv)',
    description: "Returns an equivalent interest rate for the growth of an investment." },
  { id: 'isformula', name: 'ISFORMULA', category: 'Information',
    syntax: '=ISFORMULA(reference)',
    description: "Checks whether a cell contains a formula." },
  { id: 'isref', name: 'ISREF', category: 'Information',
    syntax: '=ISREF(value)',
    description: "Checks whether a value is a valid cell reference." },
  { id: 'islogical', name: 'ISLOGICAL', category: 'Information',
    syntax: '=ISLOGICAL(value)',
    description: "Checks whether a value is TRUE or FALSE." },
  { id: 'n', name: 'N', category: 'Information',
    syntax: '=N(value)',
    description: "Converts a value to a number \u2014 text becomes 0, dates become serial numbers." },
  { id: 'sheet', name: 'SHEET', category: 'Information',
    syntax: '=SHEET([value])',
    description: "Returns the sheet number of a reference." },
  { id: 'sheets', name: 'SHEETS', category: 'Information',
    syntax: '=SHEETS([reference])',
    description: "Returns the number of sheets in a reference." },
  { id: 'errortype', name: 'ERROR.TYPE', category: 'Information',
    syntax: '=ERROR.TYPE(error_val)',
    description: "Returns a number matching a specific error type." },
  { id: 'info', name: 'INFO', category: 'Information',
    syntax: '=INFO(type_text)',
    description: "Returns information about the current operating environment." },
  { id: 'lambda', name: 'LAMBDA', category: 'Logic',
    syntax: '=LAMBDA([parameter1, ...], calculation)',
    description: "Creates a custom, reusable function using Excel's own formula language." },
  { id: 'let', name: 'LET', category: 'Logic',
    syntax: '=LET(name1, value1, [name2, value2, ...], calculation)',
    description: "Assigns names to calculation results, so a formula can reuse them." },
  { id: 'byrow', name: 'BYROW', category: 'Logic',
    syntax: '=BYROW(array, lambda)',
    description: "Applies a LAMBDA to each row of an array and returns one result per row." },
  { id: 'bycol', name: 'BYCOL', category: 'Logic',
    syntax: '=BYCOL(array, lambda)',
    description: "Applies a LAMBDA to each column of an array and returns one result per column." },
  { id: 'map', name: 'MAP', category: 'Logic',
    syntax: '=MAP(array1, lambda)',
    description: "Applies a LAMBDA to every item in an array and returns an array of results." },
  { id: 'reduce', name: 'REDUCE', category: 'Logic',
    syntax: '=REDUCE([initial_value], array, lambda)',
    description: "Reduces an array to a single accumulated value using a LAMBDA." },
  { id: 'scan', name: 'SCAN', category: 'Logic',
    syntax: '=SCAN([initial_value], array, lambda)',
    description: "Applies a LAMBDA to an array and returns each intermediate accumulated value." },
  { id: 'dsum', name: 'DSUM', category: 'Database',
    syntax: '=DSUM(database, field, criteria)',
    description: "Sums a column in a table that matches a set of conditions." },
  { id: 'daverage', name: 'DAVERAGE', category: 'Database',
    syntax: '=DAVERAGE(database, field, criteria)',
    description: "Averages a column in a table that matches a set of conditions." },
  { id: 'dcount', name: 'DCOUNT', category: 'Database',
    syntax: '=DCOUNT(database, field, criteria)',
    description: "Counts numeric cells in a column that match a set of conditions." },
  { id: 'dcounta', name: 'DCOUNTA', category: 'Database',
    syntax: '=DCOUNTA(database, field, criteria)',
    description: "Counts non-empty cells in a column that match a set of conditions." },
  { id: 'dget', name: 'DGET', category: 'Database',
    syntax: '=DGET(database, field, criteria)',
    description: "Pulls a single value from a column that matches a set of conditions." },
  { id: 'dmax', name: 'DMAX', category: 'Database',
    syntax: '=DMAX(database, field, criteria)',
    description: "Returns the largest value in a column that matches a set of conditions." },
  { id: 'dmin', name: 'DMIN', category: 'Database',
    syntax: '=DMIN(database, field, criteria)',
    description: "Returns the smallest value in a column that matches a set of conditions." },
  { id: 'dproduct', name: 'DPRODUCT', category: 'Database',
    syntax: '=DPRODUCT(database, field, criteria)',
    description: "Multiplies values in a column that match a set of conditions." },
  { id: 'dstdev', name: 'DSTDEV', category: 'Database',
    syntax: '=DSTDEV(database, field, criteria)',
    description: "Estimates standard deviation from a sample matching a set of conditions." },
  { id: 'dstdevp', name: 'DSTDEVP', category: 'Database',
    syntax: '=DSTDEVP(database, field, criteria)',
    description: "Calculates standard deviation from a full population matching a set of conditions." },
  { id: 'dvar', name: 'DVAR', category: 'Database',
    syntax: '=DVAR(database, field, criteria)',
    description: "Estimates variance from a sample matching a set of conditions." },
  { id: 'dvarp', name: 'DVARP', category: 'Database',
    syntax: '=DVARP(database, field, criteria)',
    description: "Calculates variance from a full population matching a set of conditions." },
  { id: 'bin2dec', name: 'BIN2DEC', category: 'Engineering',
    syntax: '=BIN2DEC(number)',
    description: "Converts a binary number to decimal." },
  { id: 'bin2hex', name: 'BIN2HEX', category: 'Engineering',
    syntax: '=BIN2HEX(number, [places])',
    description: "Converts a binary number to hexadecimal." },
  { id: 'bin2oct', name: 'BIN2OCT', category: 'Engineering',
    syntax: '=BIN2OCT(number, [places])',
    description: "Converts a binary number to octal." },
  { id: 'dec2bin', name: 'DEC2BIN', category: 'Engineering',
    syntax: '=DEC2BIN(number, [places])',
    description: "Converts a decimal number to binary." },
  { id: 'dec2hex', name: 'DEC2HEX', category: 'Engineering',
    syntax: '=DEC2HEX(number, [places])',
    description: "Converts a decimal number to hexadecimal." },
  { id: 'dec2oct', name: 'DEC2OCT', category: 'Engineering',
    syntax: '=DEC2OCT(number, [places])',
    description: "Converts a decimal number to octal." },
  { id: 'hex2bin', name: 'HEX2BIN', category: 'Engineering',
    syntax: '=HEX2BIN(number, [places])',
    description: "Converts a hexadecimal number to binary." },
  { id: 'hex2dec', name: 'HEX2DEC', category: 'Engineering',
    syntax: '=HEX2DEC(number)',
    description: "Converts a hexadecimal number to decimal." },
  { id: 'hex2oct', name: 'HEX2OCT', category: 'Engineering',
    syntax: '=HEX2OCT(number, [places])',
    description: "Converts a hexadecimal number to octal." },
  { id: 'oct2bin', name: 'OCT2BIN', category: 'Engineering',
    syntax: '=OCT2BIN(number, [places])',
    description: "Converts an octal number to binary." },
  { id: 'oct2dec', name: 'OCT2DEC', category: 'Engineering',
    syntax: '=OCT2DEC(number)',
    description: "Converts an octal number to decimal." },
  { id: 'oct2hex', name: 'OCT2HEX', category: 'Engineering',
    syntax: '=OCT2HEX(number, [places])',
    description: "Converts an octal number to hexadecimal." },
  { id: 'complex', name: 'COMPLEX', category: 'Engineering',
    syntax: '=COMPLEX(real_num, i_num, [suffix])',
    description: "Combines real and imaginary parts into a complex number." },
  { id: 'imabs', name: 'IMABS', category: 'Engineering',
    syntax: '=IMABS(inumber)',
    description: "Returns the absolute value of a complex number." },
  { id: 'imaginary', name: 'IMAGINARY', category: 'Engineering',
    syntax: '=IMAGINARY(inumber)',
    description: "Returns the imaginary coefficient of a complex number." },
  { id: 'imargument', name: 'IMARGUMENT', category: 'Engineering',
    syntax: '=IMARGUMENT(inumber)',
    description: "Returns the angle (argument) of a complex number, in radians." },
  { id: 'imconjugate', name: 'IMCONJUGATE', category: 'Engineering',
    syntax: '=IMCONJUGATE(inumber)',
    description: "Returns the complex conjugate of a complex number." },
  { id: 'imcos', name: 'IMCOS', category: 'Engineering',
    syntax: '=IMCOS(inumber)',
    description: "Returns the cosine of a complex number." },
  { id: 'imcosh', name: 'IMCOSH', category: 'Engineering',
    syntax: '=IMCOSH(inumber)',
    description: "Returns the hyperbolic cosine of a complex number." },
  { id: 'imcot', name: 'IMCOT', category: 'Engineering',
    syntax: '=IMCOT(inumber)',
    description: "Returns the cotangent of a complex number." },
  { id: 'imcsc', name: 'IMCSC', category: 'Engineering',
    syntax: '=IMCSC(inumber)',
    description: "Returns the cosecant of a complex number." },
  { id: 'imcsch', name: 'IMCSCH', category: 'Engineering',
    syntax: '=IMCSCH(inumber)',
    description: "Returns the hyperbolic cosecant of a complex number." },
  { id: 'imdiv', name: 'IMDIV', category: 'Engineering',
    syntax: '=IMDIV(inumber1, inumber2)',
    description: "Returns the quotient of two complex numbers." },
  { id: 'imexp', name: 'IMEXP', category: 'Engineering',
    syntax: '=IMEXP(inumber)',
    description: "Returns e raised to the power of a complex number." },
  { id: 'imln', name: 'IMLN', category: 'Engineering',
    syntax: '=IMLN(inumber)',
    description: "Returns the natural logarithm of a complex number." },
  { id: 'imlog10', name: 'IMLOG10', category: 'Engineering',
    syntax: '=IMLOG10(inumber)',
    description: "Returns the base-10 logarithm of a complex number." },
  { id: 'imlog2', name: 'IMLOG2', category: 'Engineering',
    syntax: '=IMLOG2(inumber)',
    description: "Returns the base-2 logarithm of a complex number." },
  { id: 'impower', name: 'IMPOWER', category: 'Engineering',
    syntax: '=IMPOWER(inumber, number)',
    description: "Raises a complex number to a given power." },
  { id: 'improduct', name: 'IMPRODUCT', category: 'Engineering',
    syntax: '=IMPRODUCT(inumber1, [inumber2], ...)',
    description: "Returns the product of complex numbers." },
  { id: 'imreal', name: 'IMREAL', category: 'Engineering',
    syntax: '=IMREAL(inumber)',
    description: "Returns the real coefficient of a complex number." },
  { id: 'imsec', name: 'IMSEC', category: 'Engineering',
    syntax: '=IMSEC(inumber)',
    description: "Returns the secant of a complex number." },
  { id: 'imsech', name: 'IMSECH', category: 'Engineering',
    syntax: '=IMSECH(inumber)',
    description: "Returns the hyperbolic secant of a complex number." },
  { id: 'imsin', name: 'IMSIN', category: 'Engineering',
    syntax: '=IMSIN(inumber)',
    description: "Returns the sine of a complex number." },
  { id: 'imsinh', name: 'IMSINH', category: 'Engineering',
    syntax: '=IMSINH(inumber)',
    description: "Returns the hyperbolic sine of a complex number." },
  { id: 'imsqrt', name: 'IMSQRT', category: 'Engineering',
    syntax: '=IMSQRT(inumber)',
    description: "Returns the square root of a complex number." },
  { id: 'imsub', name: 'IMSUB', category: 'Engineering',
    syntax: '=IMSUB(inumber1, inumber2)',
    description: "Returns the difference of two complex numbers." },
  { id: 'imsum', name: 'IMSUM', category: 'Engineering',
    syntax: '=IMSUM(inumber1, [inumber2], ...)',
    description: "Returns the sum of complex numbers." },
  { id: 'imtan', name: 'IMTAN', category: 'Engineering',
    syntax: '=IMTAN(inumber)',
    description: "Returns the tangent of a complex number." },
  { id: 'convert', name: 'CONVERT', category: 'Engineering',
    syntax: '=CONVERT(number, from_unit, to_unit)',
    description: "Converts a number from one measurement unit to another." },
  { id: 'delta', name: 'DELTA', category: 'Engineering',
    syntax: '=DELTA(number1, [number2])',
    description: "Tests whether two numbers are exactly equal, returning 1 or 0." },
  { id: 'gestep', name: 'GESTEP', category: 'Engineering',
    syntax: '=GESTEP(number, [step])',
    description: "Tests whether a number is greater than or equal to a threshold." },
  { id: 'erf', name: 'ERF', category: 'Engineering',
    syntax: '=ERF(lower_limit, [upper_limit])',
    description: "Returns the error function, used in probability and statistics." },
  { id: 'erfc', name: 'ERFC', category: 'Engineering',
    syntax: '=ERFC(x)',
    description: "Returns the complementary error function." },
  { id: 'besselj', name: 'BESSELJ', category: 'Engineering',
    syntax: '=BESSELJ(x, n)',
    description: "Returns the Bessel function Jn(x)." },
  { id: 'bessely', name: 'BESSELY', category: 'Engineering',
    syntax: '=BESSELY(x, n)',
    description: "Returns the Bessel function Yn(x)." },
  { id: 'besseli', name: 'BESSELI', category: 'Engineering',
    syntax: '=BESSELI(x, n)',
    description: "Returns the modified Bessel function In(x)." },
  { id: 'besselk', name: 'BESSELK', category: 'Engineering',
    syntax: '=BESSELK(x, n)',
    description: "Returns the modified Bessel function Kn(x)." },
  { id: 'encodeurl', name: 'ENCODEURL', category: 'Web',
    syntax: '=ENCODEURL(text)',
    description: "Returns a URL-encoded version of a text string." },
  { id: 'filterxml', name: 'FILTERXML', category: 'Web',
    syntax: '=FILTERXML(xml, xpath)',
    description: "Returns specific data from XML content using an XPath query." },
  { id: 'webservice', name: 'WEBSERVICE', category: 'Web',
    syntax: '=WEBSERVICE(url)',
    description: "Returns data from a web service at a given URL." },
  { id: 'betadistold', name: 'BETADIST', category: 'Compatibility',
    syntax: '=BETADIST(x, alpha, beta, [A], [B])',
    description: "Legacy version of the beta distribution \u2014 kept for compatibility with older files." },
  { id: 'binomdistold', name: 'BINOMDIST', category: 'Compatibility',
    syntax: '=BINOMDIST(number_s, trials, probability_s, cumulative)',
    description: "Legacy version of the binomial distribution \u2014 kept for compatibility with older files." },
  { id: 'chidistold', name: 'CHIDIST', category: 'Compatibility',
    syntax: '=CHIDIST(x, deg_freedom)',
    description: "Legacy version of the chi-squared distribution \u2014 kept for compatibility with older files." },
  { id: 'chiinvold', name: 'CHIINV', category: 'Compatibility',
    syntax: '=CHIINV(probability, deg_freedom)',
    description: "Legacy inverse chi-squared distribution \u2014 kept for compatibility with older files." },
  { id: 'chitestold', name: 'CHITEST', category: 'Compatibility',
    syntax: '=CHITEST(actual_range, expected_range)',
    description: "Legacy chi-squared test \u2014 kept for compatibility with older files." },
  { id: 'confidenceold', name: 'CONFIDENCE', category: 'Compatibility',
    syntax: '=CONFIDENCE(alpha, standard_dev, size)',
    description: "Legacy confidence interval formula \u2014 kept for compatibility with older files." },
  { id: 'covarold', name: 'COVAR', category: 'Compatibility',
    syntax: '=COVAR(array1, array2)',
    description: "Legacy covariance formula \u2014 kept for compatibility with older files." },
  { id: 'critbinomold', name: 'CRITBINOM', category: 'Compatibility',
    syntax: '=CRITBINOM(trials, probability_s, alpha)',
    description: "Legacy binomial criterion formula \u2014 kept for compatibility with older files." },
  { id: 'expondistold', name: 'EXPONDIST', category: 'Compatibility',
    syntax: '=EXPONDIST(x, lambda, cumulative)',
    description: "Legacy exponential distribution \u2014 kept for compatibility with older files." },
  { id: 'fdistold', name: 'FDIST', category: 'Compatibility',
    syntax: '=FDIST(x, deg_freedom1, deg_freedom2)',
    description: "Legacy F distribution \u2014 kept for compatibility with older files." },
  { id: 'finvold', name: 'FINV', category: 'Compatibility',
    syntax: '=FINV(probability, deg_freedom1, deg_freedom2)',
    description: "Legacy inverse F distribution \u2014 kept for compatibility with older files." },
  { id: 'ftestold', name: 'FTEST', category: 'Compatibility',
    syntax: '=FTEST(array1, array2)',
    description: "Legacy F-test \u2014 kept for compatibility with older files." },
  { id: 'gammadistold', name: 'GAMMADIST', category: 'Compatibility',
    syntax: '=GAMMADIST(x, alpha, beta, cumulative)',
    description: "Legacy gamma distribution \u2014 kept for compatibility with older files." },
  { id: 'gammainvold', name: 'GAMMAINV', category: 'Compatibility',
    syntax: '=GAMMAINV(probability, alpha, beta)',
    description: "Legacy inverse gamma distribution \u2014 kept for compatibility with older files." },
  { id: 'hypgeomdistold', name: 'HYPGEOMDIST', category: 'Compatibility',
    syntax: '=HYPGEOMDIST(sample_s, number_sample, population_s, number_pop)',
    description: "Legacy hypergeometric distribution \u2014 kept for compatibility with older files." },
  { id: 'loginvold', name: 'LOGINV', category: 'Compatibility',
    syntax: '=LOGINV(probability, mean, standard_dev)',
    description: "Legacy inverse lognormal distribution \u2014 kept for compatibility with older files." },
  { id: 'lognormdistold', name: 'LOGNORMDIST', category: 'Compatibility',
    syntax: '=LOGNORMDIST(x, mean, standard_dev)',
    description: "Legacy lognormal distribution \u2014 kept for compatibility with older files." },
  { id: 'negbinomdistold', name: 'NEGBINOMDIST', category: 'Compatibility',
    syntax: '=NEGBINOMDIST(number_f, number_s, probability_s)',
    description: "Legacy negative binomial distribution \u2014 kept for compatibility with older files." },
  { id: 'normdistold', name: 'NORMDIST', category: 'Compatibility',
    syntax: '=NORMDIST(x, mean, standard_dev, cumulative)',
    description: "Legacy normal distribution \u2014 kept for compatibility with older files." },
  { id: 'norminvold', name: 'NORMINV', category: 'Compatibility',
    syntax: '=NORMINV(probability, mean, standard_dev)',
    description: "Legacy inverse normal distribution \u2014 kept for compatibility with older files." },
  { id: 'normsdistold', name: 'NORMSDIST', category: 'Compatibility',
    syntax: '=NORMSDIST(z)',
    description: "Legacy standard normal distribution \u2014 kept for compatibility with older files." },
  { id: 'normsinvold', name: 'NORMSINV', category: 'Compatibility',
    syntax: '=NORMSINV(probability)',
    description: "Legacy inverse standard normal distribution \u2014 kept for compatibility with older files." },
  { id: 'percentrank', name: 'PERCENTRANK', category: 'Compatibility',
    syntax: '=PERCENTRANK(array, x, [significance])',
    description: "Legacy percentage rank formula \u2014 kept for compatibility with older files." },
  { id: 'poissonold', name: 'POISSON', category: 'Compatibility',
    syntax: '=POISSON(x, mean, cumulative)',
    description: "Legacy Poisson distribution \u2014 kept for compatibility with older files." },
  { id: 'tdistold', name: 'TDIST', category: 'Compatibility',
    syntax: '=TDIST(x, deg_freedom, tails)',
    description: "Legacy Student's t-distribution \u2014 kept for compatibility with older files." },
  { id: 'tinvold', name: 'TINV', category: 'Compatibility',
    syntax: '=TINV(probability, deg_freedom)',
    description: "Legacy inverse t-distribution \u2014 kept for compatibility with older files." },
  { id: 'weibullold', name: 'WEIBULL', category: 'Compatibility',
    syntax: '=WEIBULL(x, alpha, beta, cumulative)',
    description: "Legacy Weibull distribution \u2014 kept for compatibility with older files." },
  { id: 'ztestold', name: 'ZTEST', category: 'Compatibility',
    syntax: '=ZTEST(array, x, [sigma])',
    description: "Legacy z-test formula \u2014 kept for compatibility with older files." },
  { id: 'cubevalue', name: 'CUBEVALUE', category: 'Cube',
    syntax: '=CUBEVALUE(connection, [member_expression1], ...)',
    description: "Returns a value from a data cube connected to an external server." },
  { id: 'cubemember', name: 'CUBEMEMBER', category: 'Cube',
    syntax: '=CUBEMEMBER(connection, member_expression, [caption])',
    description: "Returns a member from a cube for verification within the cube." },
  { id: 'cubeset', name: 'CUBESET', category: 'Cube',
    syntax: '=CUBESET(connection, set_expression, [caption], [sort_order], [sort_by])',
    description: "Defines a set of members from a data cube." },
  { id: 'cubesetcount', name: 'CUBESETCOUNT', category: 'Cube',
    syntax: '=CUBESETCOUNT(set)',
    description: "Returns the number of items in a cube set." },
  { id: 'cuberankedmember', name: 'CUBERANKEDMEMBER', category: 'Cube',
    syntax: '=CUBERANKEDMEMBER(connection, set_expression, rank, [caption])',
    description: "Returns the nth ranked member from a cube set." },
  { id: 'cubekpimember', name: 'CUBEKPIMEMBER', category: 'Cube',
    syntax: '=CUBEKPIMEMBER(connection, kpi_name, kpi_property, [caption])',
    description: "Returns a key performance indicator property from a cube." },
  { id: 'cubememberproperty', name: 'CUBEMEMBERPROPERTY', category: 'Cube',
    syntax: '=CUBEMEMBERPROPERTY(connection, member_expression, property)',
    description: "Returns a property value of a cube member." },

  { id: 'tdist2t', name: 'T.DIST.2T', category: 'Statistical',
    syntax: '=T.DIST.2T(x, deg_freedom)',
    description: "Returns the two-tailed Student's t-distribution." },
  { id: 'tdistrt', name: 'T.DIST.RT', category: 'Statistical',
    syntax: '=T.DIST.RT(x, deg_freedom)',
    description: "Returns the right-tailed Student's t-distribution." },
  { id: 'chisqdistrt', name: 'CHISQ.DIST.RT', category: 'Statistical',
    syntax: '=CHISQ.DIST.RT(x, deg_freedom)',
    description: "Returns the right-tailed chi-squared distribution." },
  { id: 'fdistrt', name: 'F.DIST.RT', category: 'Statistical',
    syntax: '=F.DIST.RT(x, deg_freedom1, deg_freedom2)',
    description: "Returns the right-tailed F probability distribution." },
  { id: 'finvrt', name: 'F.INV.RT', category: 'Statistical',
    syntax: '=F.INV.RT(probability, deg_freedom1, deg_freedom2)',
    description: "Returns the inverse of the right-tailed F distribution." },
  { id: 'chisqinvrt', name: 'CHISQ.INV.RT', category: 'Statistical',
    syntax: '=CHISQ.INV.RT(probability, deg_freedom)',
    description: "Returns the inverse of the right-tailed chi-squared distribution." },
  { id: 'gamma', name: 'GAMMA', category: 'Statistical',
    syntax: '=GAMMA(number)',
    description: "Returns the gamma function value." },
  { id: 'gammaln', name: 'GAMMALN', category: 'Statistical',
    syntax: '=GAMMALN(x)',
    description: "Returns the natural logarithm of the gamma function." },
  { id: 'gammalnprecise', name: 'GAMMALN.PRECISE', category: 'Statistical',
    syntax: '=GAMMALN.PRECISE(x)',
    description: "Returns a more precise natural logarithm of the gamma function." },
  { id: 'phi', name: 'PHI', category: 'Statistical',
    syntax: '=PHI(x)',
    description: "Returns the value of the density function for a standard normal distribution." },
  { id: 'averagea', name: 'AVERAGEA', category: 'Statistical',
    syntax: '=AVERAGEA(value1, [value2], ...)',
    description: "Averages values, treating text and FALSE as 0 and TRUE as 1." },
  { id: 'maxa', name: 'MAXA', category: 'Statistical',
    syntax: '=MAXA(value1, [value2], ...)',
    description: "Returns the largest value, treating text and FALSE as 0 and TRUE as 1." },
  { id: 'mina', name: 'MINA', category: 'Statistical',
    syntax: '=MINA(value1, [value2], ...)',
    description: "Returns the smallest value, treating text and FALSE as 0 and TRUE as 1." },
  { id: 'stdeva', name: 'STDEVA', category: 'Statistical',
    syntax: '=STDEVA(value1, [value2], ...)',
    description: "Estimates standard deviation from a sample, including text and logical values." },
  { id: 'stdevpa', name: 'STDEVPA', category: 'Statistical',
    syntax: '=STDEVPA(value1, [value2], ...)',
    description: "Calculates standard deviation from a population, including text and logical values." },
  { id: 'vara', name: 'VARA', category: 'Statistical',
    syntax: '=VARA(value1, [value2], ...)',
    description: "Estimates variance from a sample, including text and logical values." },
  { id: 'varpa', name: 'VARPA', category: 'Statistical',
    syntax: '=VARPA(value1, [value2], ...)',
    description: "Calculates variance from a population, including text and logical values." },
  { id: 'leftb', name: 'LEFTB', category: 'Text',
    syntax: '=LEFTB(text, [num_bytes])',
    description: "Like LEFT, but counts bytes instead of characters \u2014 for double-byte languages." },
  { id: 'rightb', name: 'RIGHTB', category: 'Text',
    syntax: '=RIGHTB(text, [num_bytes])',
    description: "Like RIGHT, but counts bytes instead of characters \u2014 for double-byte languages." },
  { id: 'midb', name: 'MIDB', category: 'Text',
    syntax: '=MIDB(text, start_num, num_bytes)',
    description: "Like MID, but counts bytes instead of characters \u2014 for double-byte languages." },
  { id: 'lenb', name: 'LENB', category: 'Text',
    syntax: '=LENB(text)',
    description: "Like LEN, but counts bytes instead of characters \u2014 for double-byte languages." },
  { id: 'findb', name: 'FINDB', category: 'Text',
    syntax: '=FINDB(find_text, within_text, [start_num])',
    description: "Like FIND, but counts bytes instead of characters \u2014 for double-byte languages." },
  { id: 'searchb', name: 'SEARCHB', category: 'Text',
    syntax: '=SEARCHB(find_text, within_text, [start_num])',
    description: "Like SEARCH, but counts bytes instead of characters \u2014 for double-byte languages." },
  { id: 'replaceb', name: 'REPLACEB', category: 'Text',
    syntax: '=REPLACEB(old_text, start_num, num_bytes, new_text)',
    description: "Like REPLACE, but counts bytes instead of characters \u2014 for double-byte languages." },
  { id: 'dbcs', name: 'DBCS', category: 'Text',
    syntax: '=DBCS(text)',
    description: "Converts half-width characters to full-width for double-byte character sets." },
  { id: 'rtd', name: 'RTD', category: 'Lookup & Reference',
    syntax: '=RTD(prog_id, server, topic1, ...)',
    description: "Retrieves real-time data from a program that supports COM automation." },
  { id: 'ispmt', name: 'ISPMT', category: 'Financial',
    syntax: '=ISPMT(rate, per, nper, pv)',
    description: "Calculates interest paid for a specific period of a loan with straight-line principal payments." },
  { id: 'erfprecise', name: 'ERF.PRECISE', category: 'Engineering',
    syntax: '=ERF.PRECISE(x)',
    description: "Returns a more precise version of the error function." },
  { id: 'erfcprecise', name: 'ERFC.PRECISE', category: 'Engineering',
    syntax: '=ERFC.PRECISE(x)',
    description: "Returns a more precise version of the complementary error function." },
  { id: 'cell', name: 'CELL', category: 'Information',
    syntax: '=CELL(info_type, [reference])',
    description: "Returns information about the formatting, location, or contents of a cell." },
  { id: 'errortype2', name: 'NA', category: 'Information',
    syntax: '=NA()',
    description: "Returns the #N/A error value deliberately, often as a placeholder." },
];
