-- =========================================================
-- Learn With Rinkesh — Feedback system
-- Paste into Supabase → SQL Editor → New query → Run.
-- =========================================================

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  name text,
  email text,
  rating int not null,
  message text,
  page_url text,
  created_at timestamp with time zone default now()
);

alter table public.feedback enable row level security;

-- Anyone (logged in or anonymous) can submit feedback
create policy "Anyone can submit feedback"
  on public.feedback for insert
  with check (true);

-- A logged-in user can only check whether THEY have already submitted
-- feedback before (used to enforce "ask logged-in users only once")
create policy "Users can check their own feedback"
  on public.feedback for select
  using (auth.uid() = user_id);

-- Note: there is no general SELECT policy, so feedback is not readable
-- through the website itself. Rinkesh can view all submissions directly
-- in the Supabase Table Editor (project owners bypass RLS there).
