-- =========================================================
-- Learn With Rinkesh — Community Chat system
-- Paste into Supabase → SQL Editor → New query → Run.
-- =========================================================

-- Chat preference fields on profiles
alter table public.profiles
  add column if not exists chat_display_name text,
  add column if not exists chat_hide_name boolean default false,
  add column if not exists chat_disclaimer_seen boolean default false;

-- The public chat messages table
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  display_name text not null,
  message text,
  image_url text,
  created_at timestamp with time zone default now()
);

alter table public.chat_messages enable row level security;

-- This is a public community chat — anyone can read the full history
create policy "Anyone can read chat messages"
  on public.chat_messages for select
  using (true);

-- Anyone (logged in or anonymous) can post a message
create policy "Anyone can send chat messages"
  on public.chat_messages for insert
  with check (true);

-- Storage bucket for chat image attachments
insert into storage.buckets (id, name, public)
values ('chat-images', 'chat-images', true)
on conflict (id) do nothing;

create policy "Anyone can view chat images"
  on storage.objects for select
  using (bucket_id = 'chat-images');

create policy "Anyone can upload chat images"
  on storage.objects for insert
  with check (bucket_id = 'chat-images');

-- =========================================================
-- IMPORTANT MANUAL STEP:
-- For messages to appear live without refreshing, Realtime needs
-- to be turned on for this table. In the Supabase dashboard, go to
-- Database → Replication, find "chat_messages", and enable it.
-- =========================================================
